### ISSUE TITLE
Assertion Error 

### ISSUE THREAD

**Issue by NikkiBytes** [nipy/heudiconv#109]
Hey I am getting this assertion error and after studying the code I am unsure why.....

`Traceback (most recent call last):
  File "/usr/local/bin/heudiconv", line 2197, in <module>
    main()
  File "/usr/local/bin/heudiconv", line 2189, in main
    return _main(args)
  File "/usr/local/bin/heudiconv", line 2052, in _main
    min_meta=args.minmeta)
  File "/usr/local/bin/heudiconv", line 1364, in convert_dicoms
    grouping=None,  # no groupping
  File "/usr/local/bin/heudiconv", line 425, in group_dicoms_into_seqinfos
    assert studyUID == file_studyUID
AssertionError
`

**I am running heudiconv through a singularity shell on an HPC
Here is the command....

` > heudiconv  -d /lab_data/{subject}/SM*/raw/SM*/*/*.dcm -s SugarMama -f /heuristics/convertall.py -c none -o /test`

**Comment by adrose** [comment]
Hi, why was this closed? What was the solution for this error?
