### ISSUE TITLE
--overwrite mode breaks

### ISSUE THREAD

**Issue by yarikoptic** [nipy/heudiconv#154]
will provide complete recipe later, just wanted to record the fact

```shell
$> heudiconv --bids --datalad -f reproin --overwrite --files QA/sourcedata/sub-qa/ses-20180102         
INFO: Running heudiconv version 0.4      
INFO: Analyzing 5122 dicoms
INFO: Filtering out 0 dicoms based on their filename
INFO: Generated sequence info for 1 studies with 6 entries total
INFO: Processing sequence infos to deduce study/session
INFO: Fixing up protocol for 43b67d9139e8c7274578b7451ab21123
INFO: Study session for {'locator': 'dbic/QA', 'session': '20180102', 'subject': 'qa'}
INFO: Need to process 1 study sessions
INFO: PROCESSING STARTS: {'session': '20180102', 'outdir': '/home/yoh/picts/mris/dbic/QA', 'subject': 'qa'}
INFO: Processing 6 pre-sorted seqinfo entries
INFO: Reloading existing filegroup.json because /home/yoh/picts/mris/dbic/QA/.heudiconv/qa/ses-20180102/info/qa_ses-20180102.edit.txt exists
INFO: Doing conversion using dcm2niix
INFO: Converting /home/yoh/picts/mris/dbic/QA/sub-qa/ses-20180102/func/sub-qa_ses-20180102_task-rest_acq-p2Xs4X35mm_bold (200 DICOMs) -> /home/yoh/picts/mris/dbic/QA/sub-qa/ses-20180102/func . Converter: dcm2niix . Output types: ('nii.gz', 'dicom')
INFO: Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
INFO: Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
Traceback (most recent call last):
  File "/home/yoh/picts/mris/heudiconv-master/venvs/dev/bin/heudiconv", line 11, in <module>
    load_entry_point('heudiconv', 'console_scripts', 'heudiconv')()
  File "/home/yoh/picts/mris/heudiconv-master/heudiconv/cli/run.py", line 120, in main
    process_args(args)
  File "/home/yoh/picts/mris/heudiconv-master/heudiconv/cli/run.py", line 322, in process_args
    overwrite=args.overwrite,)
  File "/home/yoh/picts/mris/heudiconv-master/heudiconv/convert.py", line 194, in prep_conversion
    overwrite=overwrite,)
  File "/home/yoh/picts/mris/heudiconv-master/heudiconv/convert.py", line 278, in convert
    bids, tmpdir)
  File "/home/yoh/picts/mris/heudiconv-master/heudiconv/convert.py", line 395, in nipype_convert
    convertnode.inputs.source_names = item_dicoms
  File "/usr/lib/python2.7/dist-packages/nipype/interfaces/base.py", line 2013, in validate
    value = super(MultiPath, self).validate(object, name, newvalue)
  File "/usr/lib/python2.7/dist-packages/traits/trait_types.py", line 2337, in validate
    return TraitListObject( self, object, name, value )
  File "/usr/lib/python2.7/dist-packages/traits/trait_handlers.py", line 2313, in __init__
    raise excp
traits.trait_errors.TraitError: The trait 'source_names' of a Dcm2niixInputSpec instance is an existing file name, but the path  '/home/yoh/.tmp/heudiconvDCMUIJKkv/sub-qa_ses-20180102_task-rest_acq-p2Xs4X35mm_bold/000001.dcm' does not exist.
heudiconv --bids --datalad -f reproin --overwrite --files   43.61s user 2.00s system 96% cpu 47.127 total
```

**Comment by yarikoptic** [comment]
nah. nothing to do with --overwrite -- it just 
```
Reloading existing filegroup.json because /home/yoh/picts/mris/dbic/QA/.heudiconv/qa/ses-20180102/info/qa_ses-20180102.edit.txt exists
```
I think it all should boil down to clear(er) specification of mode of operation as already was reported in #84, which was only partially addressed in #129, and somewhat discussed/disected in #134 but we still didn't provide an explicit flag/mode to say "ignore existing .heudiconv", which is apparently also failing because remembers tempdir names now

**Comment by mgxd** [comment]
@yarikoptic is this a problem?
