### ISSUE TITLE
Docker app error on windows

### ISSUE THREAD

**Issue by hcp4715** [nipy/heudiconv#181]
Dear there,

I tried the docker app on windows and found a quite strange error.
![capture](https://user-images.githubusercontent.com/7300419/37898578-7add1c32-30e9-11e8-8155-559d6e67e9a9.PNG)

I googled for a solution for a while, and thought it might be that the directory can't be recognized by docker. Then I tried the other docker images (apline) on my pc, here is what I did with alpine:
![Uploading Capture (1).PNG…]()

I also tried to change the way to specify the direction by replacing "G:/Data.." with "/G/Data...", but it doesn't really help.

Thanks very much.

**Comment by yarikoptic** [comment]
a wild attempt -- could you try adding `--` before `nipy/heudiconv:latest`?
`--` often used among linux based tools to state that whatever comes after is not carrying options for the preceding command ... not sure if it would help , but thought might be worth trying since it smells like options parsing on windows is somewhat  odd.

Also just in case try to wrap `/data/{subj...` argument within `""`

**Comment by hcp4715** [comment]
Hi, @yarikoptic ,
Thanks very much for your quick response.

The second solution makes the code run!!

> Also just in case try to wrap `/data/{subj...` argument within ""

Then I used the code from a kind-hearted friend Peer Herholz, who had successfully converted the data. But I encountered an I/O error:

> PS C:\WINDOWS\system32> docker run --rm -it -v G:\Data\coiltest\heudiconv\dicoms:/data:ro -v G:\Data\coiltest\heudiconv\BIDS:/output  nipy/heudiconv:latest -d "/data/{subject}/*/*/*" -s 01 -f /output/heuristic_2.py -c dcm2niix -b --minmeta -o /output
> INFO: Running heudiconv version 0.5.dev1
> INFO: Need to process 1 study sessions
> INFO: PROCESSING STARTS: {'session': None, 'outdir': '/output/', 'subject': '01'}
> INFO: Processing 1547 dicoms
> INFO: Analyzing 1547 dicoms
> WARNING: dcmstack without support of pydicom >= 1.0 is detected. Adding a plug
> INFO: Generated sequence info with 6 entries
> INFO: Doing conversion using dcm2niix
> INFO: Converting /output/sub-01/func/sub-01_task-fear_bold (685 DICOMs) -> /output/sub-01/func . Converter: dcm2niix . Output types: ('nii.gz',)
> INFO: [Node] Setting-up "convert" in "/tmp/dcm2niixpeejEK/convert".
> INFO: [Node] Running "convert" ("nipype.interfaces.dcm2nii.Dcm2niix"), a CommandLine Interface with command:
> dcm2niix -b y -z i -x n -t n -m n -f func -o /tmp/dcm2niixpeejEK -s n -v n /tmp/dcm2niixpeejEK/convert/MR.1.3.12.2.1107.5.2.32.35333.2018012909524587098407178
> INFO: stdout 2018-03-26T15:25:24.106014:Chris Rorden's dcm2niiX version v1.0.20171215 GCC6.3.0 (64-bit Linux)
> INFO: stdout 2018-03-26T15:25:24.106014:Found 685 DICOM image(s)
> INFO: stdout 2018-03-26T15:25:24.106014:slices stacked despite varying acquisition numbers (if this is not desired please recompile)
> INFO: stdout 2018-03-26T15:25:24.106014:Convert 685 DICOM as /tmp/dcm2niixpeejEK/func (84x72x60x685)
> INFO: stdout 2018-03-26T15:26:06.472340:Conversion required 53.353272 seconds (43.478127 for core code).
> INFO: [Node] Finished "convert".
> Traceback (most recent call last):
>   File "/opt/conda/envs/neuro/bin/heudiconv", line 11, in <module>
>     load_entry_point('heudiconv==0.5.dev1', 'console_scripts', 'heudiconv')()
>   File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/cli/run.py", line 120, in main
>     process_args(args)
>   File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/cli/run.py", line 330, in process_args
>     overwrite=args.overwrite,)
>   File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/convert.py", line 194, in prep_conversion
>     overwrite=overwrite,)
>   File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/convert.py", line 283, in convert
>     overwrite=overwrite)
>   File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/convert.py", line 482, in save_converted_files
>     safe_copyfile(res_files, outname, overwrite)
>   File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/utils.py", line 326, in safe_copyfile
>     shutil.copyfile(src, dest)
>   File "/opt/conda/envs/neuro/lib/python2.7/shutil.py", line 98, in copyfile
>     copyfileobj(fsrc, fdst)
> IOError: [Errno 5] Input/output error

**Comment by PeerHerholz** [comment]
Hey @hcp4715 ,

as far as I can tell the conversion has worked. The problem seems to be related to copying the converted files to the output directory. Could you check if you deleted the output of the initial run of heudiconv (to get dicominfo.tsv, etc.)? Are you working remotely, e.g. using ssh?

**Comment by hcp4715** [comment]
Hi, @PeerHerholz ,
Thanks for jumping in.

For the I/O error, maybe it is because I put the data on a portable hard driver linked to my pc using a USB cable. But I guess this should work as well.

After I copy the data to my local hard driver and use the exactly the same dataset and the script you sent me, copying the converted files to the output directory still persists.

**Comment by PeerHerholz** [comment]
Just guessing now: did you also remove the output from the initial run of heudiconv (to get the dicominfo.tsv)?

**Comment by hcp4715** [comment]
@PeerHerholz I run the both of the code you've sent me (changed the directory, of course), 

first:
> docker run --rm -it -v /Users/peerherholz/Desktop/:/data:ro -v /Users/peerherholz/Desktop/Chuan-Peng/:/output  nipy/heudiconv:latest -d /data/{subject}/*/*/* -s 01 -f convertall -c none -o /output

then (the only place I changed was in bold):
> docker run --rm -it -v /Users/peerherholz/Desktop/:/data:ro -v /Users/peerherholz/Desktop/Chuan-Peng/:/output nipy/heudiconv:latest -d /data/{subject}/*/*/* -s 01 -f /**output**/heuristic_chuan-peng.py -c dcm2niix -b --minmeta  -o /output

**Comment by PeerHerholz** [comment]
Could you try removing all possible outputs from previous runs of heudiconv by:

`sudo rm -r /output/` (adapting it to your path and however this works in windows) 

and then try just try the second part, the actual run of heudiconv, again?

**Comment by hcp4715** [comment]
@PeerHerholz 
You solution is great! Finally, it works!!

**Comment by PeerHerholz** [comment]
@hcp4715, as far as I can tell, it should (of course depending on read/write/etc. stuff, but that shouldn't be a problem as it's your hard drive).

@yarikoptic do you think a small add on snippet checking if the desired output path already contains  information and if specified delete/overwrite that would be useful?

**Comment by yarikoptic** [comment]
well @PeerHerholz -- that is what that [safe_copyfile](https://github.com/nipy/heudiconv/blob/master/heudiconv/utils.py#L314) already does, so I guess it was some specific nuisance which we haven't yet checked for, e.g. a non-writeable directory or alike?

**Comment by PeerHerholz** [comment]
sorry @yarikoptic , my bad. totally didn't check closely enough and hence, missed [safe_copyfile](https://github.com/nipy/heudiconv/blob/master/heudiconv/utils.py#L314).
Hm might be, but chances are `overwrite` was set to `False`, because deleting the output from the previous run manually did the trick!?

**Comment by yarikoptic** [comment]
no appollogies are due @PeerHerholz ! that function clearly not picked up the case here, which I could only guess details of.  E.g. the file didn't exist but that mounted directory was no longer writeable or lacked permissions to be written to may be?  I guess someone on windows could try to replicate and then we could see the actual reason.  Running with --dbg would place you into the pdb debugger to figure it out interactively if needed

**Comment by hcp4715** [comment]
Hi, @yarikoptic , @PeerHerholz , I will also test it again using another driver and see whether it works.
Thanks for your help!

**Comment by PeerHerholz** [comment]
Hi all,

sorry for my late reply. 
I'll try to find a windows machine somewhere nearby and check that. 
In the meantime: @hcp4715 did you already try to replicate the error?

**Comment by hcp4715** [comment]
Hi, @PeerHerholz 
I reproduce the error, below is the error information:
`PS C:\WINDOWS\system32> docker run --rm -it -v G:\Data\coiltest\heudiconv\dicoms:/data:ro -v G:\Data\coiltest\heudiconv\
BIDS:/output  nipy/heudiconv:latest -d "/data/{subject}/*/*/*" -s 01 -f /data/heuristic_chuan-peng.py -c dcm2niix -b --m
inmeta  -o /output
INFO: Running heudiconv version 0.5.dev1
INFO: Need to process 1 study sessions
INFO: PROCESSING STARTS: {'session': None, 'outdir': '/output/', 'subject': '01'}
INFO: Processing 1547 dicoms
INFO: Analyzing 1547 dicoms
WARNING: dcmstack without support of pydicom >= 1.0 is detected. Adding a plug
INFO: Generated sequence info with 6 entries
INFO: Doing conversion using dcm2niix
INFO: Converting /output/sub-01/func/sub-01_task-rest_bold (480 DICOMs) -> /output/sub-01/func . Converter: dcm2niix . Output types: ('nii.gz',)
INFO: [Node] Setting-up "convert" in "/tmp/dcm2niixVmnN2o/convert".
INFO: [Node] Running "convert" ("nipype.interfaces.dcm2nii.Dcm2niix"), a CommandLine Interface with command:
dcm2niix -b y -z i -x n -t n -m n -f func -o /tmp/dcm2niixVmnN2o -s n -v n /tmp/dcm2niixVmnN2o/convert/MR.1.3.12.2.1107.5.2.32.35333.2018012909373867267415735
INFO: stdout 2018-04-04T14:57:22.163746:Chris Rorden's dcm2niiX version v1.0.20171215 GCC6.3.0 (64-bit Linux)
INFO: stdout 2018-04-04T14:57:22.163746:Found 480 DICOM image(s)
INFO: stdout 2018-04-04T14:57:22.163746:slices stacked despite varying acquisition numbers (if this is not desired please recompile)
INFO: stdout 2018-04-04T14:57:22.163746:Convert 480 DICOM as /tmp/dcm2niixVmnN2o/func (84x72x60x480)
INFO: stdout 2018-04-04T14:57:50.640563:Conversion required 43.875219 seconds (30.084389 for core code).
INFO: [Node] Finished "convert".
INFO: [Node] Setting-up "embedder" in "/tmp/embedmeta_cDsgp/embedder".
INFO: [Node] Running "embedder" ("nipype.interfaces.utility.wrappers.Function")
INFO: [Node] Finished "embedder".
INFO: Post-treating /output/sub-01/func/sub-01_task-rest_bold.json file
INFO: Converting /output/sub-01/anat/sub-01_T1w (224 DICOMs) -> /output/sub-01/anat . Converter: dcm2niix . Output types: ('nii.gz',)
INFO: [Node] Setting-up "convert" in "/tmp/dcm2niixTcQ8NX/convert".
INFO: [Node] Running "convert" ("nipype.interfaces.dcm2nii.Dcm2niix"), a CommandLine Interface with command:
dcm2niix -b y -z i -x n -t n -m n -f anat -o /tmp/dcm2niixTcQ8NX -s n -v n /tmp/dcm2niixTcQ8NX/convert/MR.1.3.12.2.1107.5.2.32.35333.2018012910140393303031537
INFO: stdout 2018-04-04T14:58:00.243083:Chris Rorden's dcm2niiX version v1.0.20171215 GCC6.3.0 (64-bit Linux)
INFO: stdout 2018-04-04T14:58:00.243083:Found 224 DICOM image(s)
INFO: stdout 2018-04-04T14:58:00.243083:Convert 224 DICOM as /tmp/dcm2niixTcQ8NX/anat (320x320x224x1)
INFO: stdout 2018-04-04T14:58:04.981574:Conversion required 9.706465 seconds (5.310192 for core code).
INFO: [Node] Finished "convert".
INFO: [Node] Setting-up "embedder" in "/tmp/embedmetatjbJ7o/embedder".
INFO: [Node] Running "embedder" ("nipype.interfaces.utility.wrappers.Function")
INFO: [Node] Finished "embedder".
INFO: Post-treating /output/sub-01/anat/sub-01_T1w.json file
INFO: Converting /output/sub-01/func/sub-01_task-test_bold (685 DICOMs) -> /output/sub-01/func . Converter: dcm2niix . Output types: ('nii.gz',)
INFO: [Node] Setting-up "convert" in "/tmp/dcm2niixOhLLin/convert".
INFO: [Node] Running "convert" ("nipype.interfaces.dcm2nii.Dcm2niix"), a CommandLine Interface with command:
dcm2niix -b y -z i -x n -t n -m n -f func -o /tmp/dcm2niixOhLLin -s n -v n /tmp/dcm2niixOhLLin/convert/MR.1.3.12.2.1107.5.2.32.35333.2018012909524587098407178
INFO: stdout 2018-04-04T14:58:27.367660:Chris Rorden's dcm2niiX version v1.0.20171215 GCC6.3.0 (64-bit Linux)
INFO: stdout 2018-04-04T14:58:27.367660:Found 685 DICOM image(s)
INFO: stdout 2018-04-04T14:58:27.367660:slices stacked despite varying acquisition numbers (if this is not desired please recompile)
INFO: stdout 2018-04-04T14:58:27.367660:Convert 685 DICOM as /tmp/dcm2niixOhLLin/func (84x72x60x685)
INFO: stdout 2018-04-04T14:59:06.873361:Conversion required 59.899082 seconds (41.685410 for core code).
INFO: [Node] Finished "convert".
Traceback (most recent call last):
  File "/opt/conda/envs/neuro/bin/heudiconv", line 11, in <module>
    load_entry_point('heudiconv==0.5.dev1', 'console_scripts', 'heudiconv')()
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/cli/run.py", line 120, in main
    process_args(args)
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/cli/run.py", line 330, in process_args
    overwrite=args.overwrite,)
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/convert.py", line 194, in prep_conversion
    overwrite=overwrite,)
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/convert.py", line 283, in convert
    overwrite=overwrite)
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/convert.py", line 482, in save_converted_files
    safe_copyfile(res_files, outname, overwrite)
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/utils.py", line 326, in safe_copyfile
    shutil.copyfile(src, dest)
  File "/opt/conda/envs/neuro/lib/python2.7/shutil.py", line 98, in copyfile
    copyfileobj(fsrc, fdst)
IOError: [Errno 5] Input/output error`

The difference to the error last time is that the T1 data is ok, but func file are not completed. As you can see from the picture below, the upper part is the normal output from local driver, the lower part is the output from the usb driver.

![capture](https://user-images.githubusercontent.com/7300419/38319254-ac372648-3831-11e8-9abe-f9f4c8530829.PNG)
