### ISSUE TITLE
Crashes on call without args

### ISSUE THREAD

**Issue by mih** [nipy/heudiconv#210]
```
% heudiconv
INFO: Running heudiconv version 0.5.dev1
Traceback (most recent call last):
  File "/home/mih/env/datalad3-dev/bin/heudiconv", line 11, in <module>
    load_entry_point('heudiconv', 'console_scripts', 'heudiconv')()
  File "/home/mih/hacking/heudiconv/heudiconv/cli/run.py", line 120, in main
    process_args(args)
  File "/home/mih/hacking/heudiconv/heudiconv/cli/run.py", line 240, in process_args
    heuristic = load_heuristic(args.heuristic)
  File "/home/mih/hacking/heudiconv/heudiconv/utils.py", line 276, in load_heuristic
    if os.path.sep in heuristic or os.path.lexists(heuristic):
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by mvdoc** [comment]
I think this is addressed by #209
