### ISSUE TITLE
heudiconv dry run error - problem with dicoms?

### ISSUE THREAD

**Issue by zhenghanQ** [nipy/heudiconv#212]
```
(neuro) root@5c7844020115:/data# heudiconv -d /data/{subject}/*/*.IMA -s QLAB_BLAST_20180501_123537_169000 -f convertall -c none -o /output
INFO: Running heudiconv version 0.5.dev1
INFO: Need to process 1 study sessions
INFO: PROCESSING STARTS: {'session': None, 'outdir': '/output/', 'subject': 'QLAB_BLAST_20180501_123537_169000'}
INFO: Processing 10699 dicoms
INFO: Analyzing 10699 dicoms
Traceback (most recent call last):
  File "/opt/conda/envs/neuro/bin/heudiconv", line 11, in <module>
    load_entry_point('heudiconv==0.5.dev1', 'console_scripts', 'heudiconv')()
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/cli/run.py", line 125, in main
    process_args(args)
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/cli/run.py", line 338, in process_args
    overwrite=args.overwrite,)
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/convert.py", line 159, in prep_conversion
    grouping=None)
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/dicoms.py", line 62, in group_dicoms_into_seqinfos
    mw = ds.wrapper_from_data(dcm.read_file(filename, force=True))
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/nibabel/nicom/dicomwrappers.py", line 82, in wrapper_from_data
    csa = csar.get_csa_header(dcm_data)
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/nibabel/nicom/csareader.py", line 71, in get_csa_header
    return read(tag.value)
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/nibabel/nicom/csareader.py", line 126, in read
    MAX_CSA_ITEMS, n_items))
nibabel.nicom.csareader.CSAReadError: Expected <= 199 tags, got 210
```

**Comment by mgxd** [comment]
this was fixed in nipy/nibabel#690
