### ISSUE TITLE
Heudiconv problems with dcmstack

### ISSUE THREAD

**Issue by sento4000** [nipy/heudiconv#213]
Hi guys,

My name is Vicente and I have a bug in heudiconv:
Now that I am runing heudiconv with python 2.7 this error appears in some subjects:

Traceback (most recent call last):
File "/opt/anaconda2/bin/heudiconv", line 11, in <module>
sys.exit(main())
File "​/​o​p​t​/​a​n​a​c​o​n​d​a​2​/​l​i​b​/​p​y​t​h​o​n​2​.​7​/​s​i​t​e​-​p​a​c​k​a​g​e​s​/​h​e​u​d​i​c​onv/cli/run.py", line 120, in main
process_args(args)
File "​/​o​p​t​/​a​n​a​c​o​n​d​a​2​/​l​i​b​/​p​y​t​h​o​n​2​.​7​/​s​i​t​e​-​p​a​c​k​a​g​e​s​/​h​e​u​d​i​c​onv/cli/run.py", line 330, in process_args
overwrite=args.overwrite,)
File "​/​o​p​t​/​a​n​a​c​o​n​d​a​2​/​l​i​b​/​p​y​t​h​o​n​2​.​7​/​s​i​t​e​-​p​a​c​k​a​g​e​s​/​h​e​u​d​i​c​onv/convert.py", line 156, in prep_conversion
grouping=None)
File "​/​o​p​t​/​a​n​a​c​o​n​d​a​2​/​l​i​b​/​p​y​t​h​o​n​2​.​7​/​s​i​t​e​-​p​a​c​k​a​g​e​s​/​h​e​u​d​i​c​onv/dicoms.py", line 59, in group_dicoms_into_seqinfos
from heudiconv.external.dcmstack import ds
File "​/​o​p​t​/​a​n​a​c​o​n​d​a​2​/​l​i​b​/​p​y​t​h​o​n​2​.​7​/​s​i​t​e​-​p​a​c​k​a​g​e​s​/​h​e​u​d​i​c​onv/external/dcmstack.py", line 8, in <module>
import dcmstack as ds
ImportError: No module named dcmstack

My IT departmen says that dcmstack is installed, so he think there may be a problem with the dependencies, could you tell me the specific versions of the dependencies?

**Comment by yarikoptic** [comment]
Ah them where is it installed, if they did install it?  May be it is in a different environment (needs to be in this conda one)
