### ISSUE TITLE
nipype.interfaces.dcm2nii import Dcm2niix >> ImportError: cannot import name Dcm2niix

### ISSUE THREAD

**Issue by tedstrauss** [nipy/heudiconv#216]
I am getting the following error when running heudiconv natively, i.e. not in docker.
dcm2niix is installed and working.

```
Traceback (most recent call last):
  File "/usr/bin/heudiconv", line 9, in <module>
    load_entry_point('heudiconv==0.5', 'console_scripts', 'heudiconv')()
  File "/usr/lib/python2.7/dist-packages/heudiconv/cli/run.py", line 120, in main
    process_args(args)
  File "/usr/lib/python2.7/dist-packages/heudiconv/cli/run.py", line 330, in process_args
    overwrite=args.overwrite,)
  File "/usr/lib/python2.7/dist-packages/heudiconv/convert.py", line 194, in prep_conversion
    overwrite=overwrite,)
  File "/usr/lib/python2.7/dist-packages/heudiconv/convert.py", line 278, in convert
    bids, tmpdir)
  File "/usr/lib/python2.7/dist-packages/heudiconv/convert.py", line 389, in nipype_convert
    from nipype.interfaces.dcm2nii import Dcm2niix
ImportError: cannot import name Dcm2niix

```

**Comment by mgxd** [comment]
@tedstrauss can you ensure you have the latest version of nipype?

**Comment by tedstrauss** [comment]
```
> pip show nipype
---                                                                        
Name: nipype
Version: 0.10.0
Location: /usr/lib/python2.7/dist-packages
Requires
```

**Comment by mgxd** [comment]
yeah that's ancient, we're on `1.0.4`

try `pip install -U nipype`

**Comment by tedstrauss** [comment]
That command errored out, starting with many occurrences of this: `SyntaxError: encoding problem: utf8 with BOM`

```
Found existing installation: nipype 0.10.0
    Not uninstalling nipype at /usr/lib/python2.7/dist-packages, owned by OS
Compiling /tmp/pip_build_tstrauss/nipype/nipype/interfaces/mipav/developer.py ...
  File "/tmp/pip_build_tstrauss/nipype/nipype/interfaces/mipav/developer.py", line 0
SyntaxError: encoding problem: utf8 with BOM

Compiling /tmp/pip_build_tstrauss/nipype/nipype/interfaces/semtools/brains/classify.py ...
  File "/tmp/pip_build_tstrauss/nipype/nipype/interfaces/semtools/brains/classify.py", line 0
SyntaxError: encoding problem: utf8 with BOM

....
````

**Comment by mgxd** [comment]
I'd recommend uninstalling your old version first (depending on how you installed this, you may have to use `sudo rm -rf /usr/lib/python2.7/dist-packages/nipype`)

Have you tried setting up a miniconda environment? That could be a nice way to start fresh and avoid legacy incompatibilities.

**Comment by tedstrauss** [comment]
ok i'll work on that, and come back to this thread next week. thanks

**Comment by yarikoptic** [comment]
so is the issue still persists and it is not just a matter of "confused installation"? if so -- please reopen
