### ISSUE TITLE
datalad option fails with: "warning: setlocale: LC_ALL: cannot change locale (en_CA.ISO-8859-1)"

### ISSUE THREAD

**Issue by tedstrauss** [nipy/heudiconv#228]
At the end of a successful run, the datalad step fails with this: 

```
> heudiconv -f ./reproin_mni.py --bids --datalad -o ~/Documents/heudi/subject -d '/scratch/box/webdav/box/MRI/*{subject}*/*' -s YA09_FDGTreadmill_20170822_121341530
INFO: Running heudiconv version 0.5.1
INFO: Need to process 1 study sessions
INFO: PROCESSING STARTS: {'session': None, 'outdir': '/home/bic/tstrauss/Documents/heudi/subject/', 'subject': 'YA09_FDGTreadmill_20170822_121341530'}
INFO: Processing 231 dicoms
WARNING: YA09_FDGTreadmill_20170822_121341530 contained nonalphanumeric character(s), subject ID was cleaned to be YA09FDGTreadmill20170822121341530
INFO: Analyzing 231 dicoms
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: reproim filter_files: line 268
INFO: Filtering out 0 dicoms based on their filename
/usr/local/lib/python2.7/dist-packages/dicom/__init__.py:53: UserWarning: 
This code is using an older version of pydicom, which is no longer 
maintained as of Jan 2017.  You can access the new pydicom features and API 
by installing `pydicom` from PyPI.
See 'Transitioning to pydicom 1.x' section at pydicom.readthedocs.org 
for more information.

  warnings.warn(msg)
INFO: File /scratch/box/webdav/box/MRI/YA09_FDGTreadmill_20170822_121341530/YA09_FDGTreadmill_20170822_121341530_localizer_20170822120034_1.nii is missing any StudyInstanceUID
WARNING: Ignoring /scratch/box/webdav/box/MRI/YA09_FDGTreadmill_20170822_121341530/YA09_FDGTreadmill_20170822_121341530_localizer_20170822120034_1.nii since not quite a "normal" DICOM: 'FileDataset' object has no attribute 'SeriesNumber'
INFO: File /scratch/box/webdav/box/MRI/YA09_FDGTreadmill_20170822_121341530/YA09_FDGTreadmill_20170822_121341530_localizer_20170822120034_1a.nii is missing any StudyInstanceUID
WARNING: Ignoring /scratch/box/webdav/box/MRI/YA09_FDGTreadmill_20170822_121341530/YA09_FDGTreadmill_20170822_121341530_localizer_20170822120034_1a.nii since not quite a "normal" DICOM: 'FileDataset' object has no attribute 'SeriesNumber'
INFO: File /scratch/box/webdav/box/MRI/YA09_FDGTreadmill_20170822_121341530/YA09_FDGTreadmill_20170822_121341530_localizer_20170822120034_1b.nii is missing any StudyInstanceUID
WARNING: Ignoring /scratch/box/webdav/box/MRI/YA09_FDGTreadmill_20170822_121341530/YA09_FDGTreadmill_20170822_121341530_localizer_20170822120034_1b.nii since not quite a "normal" DICOM: 'FileDataset' object has no attribute 'SeriesNumber'
INFO: File /scratch/box/webdav/box/MRI/YA09_FDGTreadmill_20170822_121341530/YA09_FDGTreadmill_20170822_121341530_t1_mprage_0.9_iso_20170822120034_2.nii is missing any StudyInstanceUID
WARNING: Ignoring /scratch/box/webdav/box/MRI/YA09_FDGTreadmill_20170822_121341530/YA09_FDGTreadmill_20170822_121341530_t1_mprage_0.9_iso_20170822120034_2.nii since not quite a "normal" DICOM: 'FileDataset' object has no attribute 'SeriesNumber'
INFO: Generated sequence info with 2 entries
INFO: reproim infotodict: line 420
INFO: reproim fix_seqinfo: line 383
INFO: reproim fix_canceled_run: line 338
INFO: reproim get_unique: line 645
INFO: reproim get_unique: line 645
INFO: reproim md5sum: line 319
INFO: Processing 2 seqinfo entries
INFO: reproim infotodict: line 424
INFO: reproim infotodict: line 431
INFO: reproim infotodict: line 436
INFO: reproim parse_dbic_protocol_name: line 761... localizer
INFO: reproim infotodict 476: if not regd {'seqtype': 'localizer'}
INFO: reproim infotodict: line 478
INFO: reproim infotodict: line 519
INFO: reproim infotodict: line 567
INFO: *** reproim infodict: line 595 ***
INFO: *** reproim infodict: line 601 ***
INFO: reproim create_key: line 304
INFO: reproim infotodict: line 436
INFO: reproim parse_dbic_protocol_name: line 761... t1_mprage_0.9_iso
INFO: reproim infotodict 476: if not regd {'seqtype': 't1', 'bids': 'mprage_0.9_iso'}
INFO: reproim infotodict: line 478
INFO: reproim infotodict: line 519
INFO: reproim infotodict: line 567
INFO: *** reproim infodict: line 595 ***
INFO: *** reproim infodict: line 601 ***
INFO: reproim create_key: line 304
INFO: reproim get_dups_marked: line 617
INFO: Doing conversion using dcm2niix
INFO: Converting /home/bic/tstrauss/Documents/heudi/subject/sub-YA09FDGTreadmill20170822121341530/localizer/sub-YA09FDGTreadmill20170822121341530_ (3 DICOMs) -> /home/bic/tstrauss/Documents/heudi/subject/sub-YA09FDGTreadmill20170822121341530/localizer . Converter: dcm2niix . Output types: ('nii.gz', 'dicom')
INFO: [Node] Setting-up "convert" in "/tmp/dcm2niixPQ_VLx/convert".
INFO: [Node] Running "convert" ("nipype.interfaces.dcm2nii.Dcm2niix"), a CommandLine Interface with command:
dcm2niix -b y -z y -x n -t n -m n -f localizer -o . -s n -v n /tmp/dcm2niixPQ_VLx/convert
INFO: stdout 2018-07-09T14:29:43.312129:Chris Rorden's dcm2niiX version v1.0.20170130 (64-bit Linux)
INFO: stdout 2018-07-09T14:29:43.312129:Found 3 DICOM image(s)
INFO: stdout 2018-07-09T14:29:43.312129:slices not stacked: orientation varies (localizer?) [0 1 0 0 0 -1] != [1 0 0 0 1 0]
INFO: stdout 2018-07-09T14:29:43.312129:Convert 1 DICOM as ./localizer (512x512x1x1)
INFO: stdout 2018-07-09T14:29:43.312129:Warning: Check that 2D images are not mirrored.
INFO: stdout 2018-07-09T14:29:43.312129:compress: "/usr/bin/pigz" -n -f "./localizer.nii"
INFO: stdout 2018-07-09T14:29:43.312129:slices not stacked: orientation varies (localizer?) [1 0 0 0 1 0] != [1 0 0 0 0 -1]
INFO: stdout 2018-07-09T14:29:43.312129:Convert 1 DICOM as ./localizera (512x512x1x1)
INFO: stdout 2018-07-09T14:29:43.312129:Warning: Check that 2D images are not mirrored.
INFO: stdout 2018-07-09T14:29:43.312129:compress: "/usr/bin/pigz" -n -f "./localizera.nii"
INFO: stdout 2018-07-09T14:29:43.312129:Warning: Weird CSA 'ProtocolSliceNumber' (2): SPATIAL, SLICE-ORDER AND DTI TRANSFORMS UNTESTED
INFO: stdout 2018-07-09T14:29:43.312129:Convert 1 DICOM as ./localizerb (512x512x1x1)
INFO: stdout 2018-07-09T14:29:43.312129:Warning: Check that 2D images are not mirrored.
INFO: stdout 2018-07-09T14:29:43.312129:compress: "/usr/bin/pigz" -n -f "./localizerb.nii"
INFO: stdout 2018-07-09T14:29:43.312129:Conversion required 0.018405 seconds.
INFO: [Node] Finished "convert".
WARNING: For now not embedding BIDS and info generated .nii.gz itself since sequence produced multiple files
INFO: Converting /home/bic/tstrauss/Documents/heudi/subject/sub-YA09FDGTreadmill20170822121341530/t1/sub-YA09FDGTreadmill20170822121341530_mpragments/heudi/subject/sub-YA09FDGTreadmill20170822121341530/t1 . Converter: dcm2niix . Output types: ('nii.gz', 'dicom')
INFO: [Node] Setting-up "convert" in "/tmp/dcm2niix4YSr5b/convert".
INFO: [Node] Running "convert" ("nipype.interfaces.dcm2nii.Dcm2niix"), a CommandLine Interface with command:
dcm2niix -b y -z y -x n -t n -m n -f t1 -o . -s n -v n /tmp/dcm2niix4YSr5b/convert
INFO: stdout 2018-07-09T14:29:49.798496:Chris Rorden's dcm2niiX version v1.0.20170130 (64-bit Linux)
INFO: stdout 2018-07-09T14:29:49.798496:Found 224 DICOM image(s)
INFO: stdout 2018-07-09T14:29:49.798496:Convert 224 DICOM as ./t1 (256x256x224x1)
INFO: stdout 2018-07-09T14:29:52.603312:compress: "/usr/bin/pigz" -n -f "./t1.nii"
INFO: stdout 2018-07-09T14:29:52.603312:Conversion required 0.615262 seconds.
INFO: [Node] Finished "convert".
INFO: Populating template files under /home/bic/tstrauss/Documents/heudi/subject/
INFO: PROCESSING DONE: {'session': None, 'outdir': '/home/bic/tstrauss/Documents/heudi/subject/', 'subject': 'YA09_FDGTreadmill_20170822_1213415
Traceback (most recent call last):                                                                                                                                               
  File "/usr/local/bin/heudiconv", line 11, in <module>
    load_entry_point('heudiconv==0.5.1', 'console_scripts', 'heudiconv')()
  File "/usr/local/lib/python2.7/dist-packages/heudiconv-0.5.1-py2.7.egg/heudiconv/cli/run.py", line 125, in main
    process_args(args)
  File "/usr/local/lib/python2.7/dist-packages/heudiconv-0.5.1-py2.7.egg/heudiconv/cli/run.py", line 351, in process_args
    add_to_datalad(outdir, study_outdir, msg, args.bids)
  File "/usr/local/lib/python2.7/dist-packages/heudiconv-0.5.1-py2.7.egg/heudiconv/external/dlad.py", line 100, in add_to_datalad
    ds.add('.gitattributes', to_git=True, save=False)
  File "/usr/local/lib/python2.7/dist-packages/datalad-0.10.1-py2.7.egg/datalad/distribution/dataset.py", line 444, in apply_func
    return f(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/datalad-0.10.1-py2.7.egg/datalad/interface/utils.py", line 478, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/datalad-0.10.1-py2.7.egg/datalad/interface/utils.py", line 466, in return_func
    results = list(results)
  File "/usr/local/lib/python2.7/dist-packages/datalad-0.10.1-py2.7.egg/datalad/interface/utils.py", line 421, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/usr/local/lib/python2.7/dist-packages/datalad-0.10.1-py2.7.egg/datalad/interface/utils.py", line 490, in _process_results
    for res in results:
  File "/usr/local/lib/python2.7/dist-packages/datalad-0.10.1-py2.7.egg/datalad/distribution/add.py", line 215, in __call__
    GitRepo(refds_path).get_hexsha() \
  File "/usr/local/lib/python2.7/dist-packages/datalad-0.10.1-py2.7.egg/datalad/support/gitrepo.py", line 1189, in get_hexsha
    raise e
datalad.support.exceptions.CommandError: CommandError: command '['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'show', '--no-patch', '--format=%H', '--']' failed with exitcode 128
Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'show', '--no-patch', '--format=%H', '--'] under '/home/bic/tstrauss/Documents/heudi/subject'. Exit code=128. out= err=/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_CA.ISO-8859-1)
fatal: Not a git repository (or any parent up to mount point /home/bic)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

```

**Comment by yarikoptic** [comment]
So it seems it did generate/found(?) dataset somewhere... what if you run `heudiconv` with `--dbg` so you would get into debugger whenever problem happens, and then use 'u' command , to get to `.get_hexsha` invocation -- do `print refds_path`, and then 'u' a few times more to get to the point of `ds.add()` and `print ds` right there to see where is the dataset.?  any specifics on how/where your output directory is and its relationship to /home/bic? (bind mount/symlink/...)?

**Comment by tedstrauss** [comment]
I updated the trace above with the full trace.

**Comment by yarikoptic** [comment]
Thanks, but not sure if that helps much.  Somehow git freaks out running `git status` under /home/bic/tstrauss/Documents/heudi/subject .  Does `git status` work for you under `~/Documents/heudi/subject`?  
Was it some existing directory before you ran this command or you do always cleanup before trying to get an initial run finally working?

**Comment by yarikoptic** [comment]
re locale warning
- how was git-annex installed -- by admin or user?  from standalone build?  is user standalone - is there `.cache/git-annex/locales/`?  Are you admin there - could you try running some git annex command as root (AFAIK it might populate locales then...)
- would it work if you set DATALAD_USE_DEFAULT_GIT=1 for that heudiconv run? (then datalad would use system wide git, instead of possibly the one shipped with git annex.
