### ISSUE TITLE
ValueError triggered by "File not large enough"

### ISSUE THREAD

**Issue by oesteban** [nipy/heudiconv#300]
### Summary
```
INFO: stdout 2019-01-29T22:50:52.370390:File not large enough to store image data: /tmp/dcm2niixFi9cD_/convert/1.2.840.113745.101000.1111000.41962.43.16921209-10-131-1misg2z.dcm
WARNING: [Node] Error on "convert" (/tmp/dcm2niixFi9cD_/convert)
Traceback (most recent call last):
  File "/opt/conda/envs/neuro/bin/heudiconv", line 11, in <module>
    load_entry_point('heudiconv==0.5.2.dev0', 'console_scripts', 'heudiconv')()
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/cli/run.py", line 125, in main
    process_args(args)
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/cli/run.py", line 338, in process_args
    overwrite=args.overwrite,)
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/convert.py", line 197, in prep_conversion
    overwrite=overwrite,)
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/convert.py", line 281, in convert
    bids, tmpdir)
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/convert.py", line 409, in nipype_convert
    eg = convertnode.run()
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 480, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 564, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 644, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/nipype/interfaces/base/core.py", line 521, in run
    runtime = self._run_interface(runtime)
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/nipype/interfaces/dcm2nii.py", line 414, in _run_interface
    self.bids) = self._parse_stdout(runtime.stdout)
ValueError: need more than 3 values to unpack
```

### Platform details:

Choose one:
- [ ] Local environment

- [x] Container

Singularity image built with docker2singularity

- Heudiconv version: 
0.5.2-dev

**Comment by oesteban** [comment]
```
singularity exec /share/PI/russpold/singularity_images/nipy_heudiconv_0.5.2-dev-2018-07-05-c29cd0b09a57.img dcm2niix sourcedata/0063/scans/10-BOLD_AP_Rest_1_BIC/DICOM/1.2.840.113745.101000.1111000.41962.43.16921209-10-131-1misg2z.dcm
Chris Rorden's dcm2niiX version v1.0.20180622 GCC6.3.0 (64-bit Linux)
Found 410 DICOM file(s)
slices stacked despite varying acquisition numbers (if this is not desired please recompile)
File not large enough to store image data: sourcedata/0063/scans/10-BOLD_AP_Rest_1_BIC/DICOM/1.2.840.113745.101000.1111000.41962.43.16921209-10-131-1misg2z.dcm
```

I have found that there is a similar file in another directory under the same subject, also 410 long and with the same prefix (10) in the protocol:
```
singularity exec /share/PI/russpold/singularity_images/nipy_heudiconv_0.5.2-dev-2018-07-05-c29cd0b09a57.img dcm2niix sourcedata/0063/scans/10/DICOM/1.2.840.113745.101000.1111000.41962.43.16921209-10-131-1misg2z.dcm
Chris Rorden's dcm2niiX version v1.0.20180622 GCC6.3.0 (64-bit Linux)
Found 410 DICOM file(s)
slices stacked despite varying acquisition numbers (if this is not desired please recompile)
CSA slice timing based on 2nd volume, 1st volume corrupted (CMRR bug, range 0..6762.5, TR=1000ms)
Convert 410 DICOM as sourcedata/0063/scans/10/DICOM/DICOM_BOLD_AP_Rest_1_BIC_20141121161326_10 (108x108x70x410)
Conversion required 20.837097 seconds (3.101998 for core code).
```

So I'm thinking that maybe the dataset is just corrupted. Maybe you can use this feedback to allow heudiconv handle the situation in a more informative way, but it seems that this is a problem of the dataset.
