### ISSUE TITLE
JSONDecodeError: Extra data

### ISSUE THREAD

**Issue by oesteban** [nipy/heudiconv#311]
### Summary

After updating my docker images to `nipy/heudiconv:latest` and `nipy/heudiconv:unstable`, and checking that both indicated version 0.5.4.dev1:

- `nipy/heudiconv:latest` did not solve #51 .
- `nipy/heudiconv:unstable` solved #51, but the following error happens now:

```
INFO: Post-treating /oak/stanford/groups/russpold/data/BSNIP1/sub-S1802FQX1/func/sub-S1802FQX1_task-rest_bold.json file
INFO: Populating template files under /oak/stanford/groups/russpold/data/BSNIP1/
Traceback (most recent call last):
  File "/opt/miniconda-latest/bin/heudiconv", line 11, in <module>
    load_entry_point('heudiconv', 'console_scripts', 'heudiconv')()
  File "/src/heudiconv/heudiconv/cli/run.py", line 127, in main
    process_args(args)
  File "/src/heudiconv/heudiconv/cli/run.py", line 341, in process_args
    dcmconfig=args.dcmconfig,)
  File "/src/heudiconv/heudiconv/convert.py", line 212, in prep_conversion
    getattr(heuristic, 'DEFAULT_FIELDS', {}))
  File "/src/heudiconv/heudiconv/bids.py", line 77, in populate_bids_templates
    populate_aggregated_jsons(path)
  File "/src/heudiconv/heudiconv/bids.py", line 164, in populate_aggregated_jsons
    j = load_json(task_file)
  File "/src/heudiconv/heudiconv/utils.py", line 174, in load_json
    data = json.load(fp)
  File "/opt/miniconda-latest/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/opt/miniconda-latest/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/opt/miniconda-latest/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 23 column 4 (char 638)
```

### Platform details:

Choose one:
- [ ] Local environment

- [x] Container

- Heudiconv version: 

0.5.4.dev1

**Comment by mgxd** [comment]
@oesteban looks like your root level `task-rest_bold.json` was incorrectly generated/modified - if you can, please share the file and I'll take a look

**Comment by oesteban** [comment]
It does look bad:

```
{
  "AcquisitionMatrixPE": 64,
  "AcquisitionNumber": 1,
  "BaseResolution": 64,
  "CogAtlasID": "TODO",
  "ConversionSoftware": "dcm2niix",
  "ConversionSoftwareVersion": "v1.0.20180622 GCC6.3.0",
  "InPlanePhaseEncodingDirectionDICOM": "COL",
  "MRAcquisitionType": "2D",
  "MagneticFieldStrength": 3,
  "Manufacturer": "Siemens",
  "Modality": "MR",
  "PartialFourier": 1,
  "PatientPosition": "HFS",
  "PercentPhaseFOV": 100,
  "PhaseEncodingDirection": "j-",
  "PhaseEncodingSteps": 64,
  "PhaseResolution": 1,
  "ReconMatrixPE": 64,
  "ScanOptions": "FS",
  "SequenceVariant": "SK",
  "TaskName": "TODO: full task name for rest"
}  "dcmmeta_reorient_transform": [
    [0.0, -1.0, 0.0, 63.0],
    [1.0, 0.0, 0.0, 0.0],
    [0.0, 0.0, 1.0, 0.0],
    [0.0, 0.0, 0.0, 1.0]
],
  "dcmmeta_slice_dim": 2,
  "dcmmeta_version": 0.6}
```

**Comment by mgxd** [comment]
I'm not entirely sure how this nonJSON JSON was created - are you altering this file at all? Or running multiple subjects in parallel?

Sidenote: have you tried converting with the `--minmeta` flag? This will simplify your BIDS sidecar files to just the fields provided by dcm2niix.
