### ISSUE TITLE
AssertionError line 239 in Utils.py

### ISSUE THREAD

**Issue by greydongilmore** [nipy/heudiconv#341]
### Summary
 
```
Traceback (most recent call last):
  File "/home/ggilmore/.local/bin/heudiconv", line 11, in <module>
    load_entry_point('heudiconv==0.5.4.dev1', 'console_scripts', 'heudiconv')()
  File "/home/ggilmore/.local/lib/python2.7/site-packages/heudiconv/cli/run.py", line 127, in main
    process_args(args)
  File "/home/ggilmore/.local/lib/python2.7/site-packages/heudiconv/cli/run.py", line 341, in process_args
    dcmconfig=args.dcmconfig,)
  File "/home/ggilmore/.local/lib/python2.7/site-packages/heudiconv/convert.py", line 199, in prep_conversion
    dcmconfig=dcmconfig,)
  File "/home/ggilmore/.local/lib/python2.7/site-packages/heudiconv/convert.py", line 318, in convert
    treat_infofile(scaninfo)
  File "/home/ggilmore/.local/lib/python2.7/site-packages/heudiconv/utils.py", line 252, in treat_infofile
    j_pretty = json_dumps_pretty(j_slim, indent=2, sort_keys=True)
  File "/home/ggilmore/.local/lib/python2.7/site-packages/heudiconv/utils.py", line 239, in json_dumps_pretty
    "Values differed when they should have not. "\
AssertionError: Values differed when they should have not. Report to the heudiconv developers
```

This works for all my scan sequences except I get this assertion failure on my CT study series. Could this be an issue with the CT sequence?

### Platform details:

Choose one:
- [x ] Local environment

Ubuntu 16.04, python 2.7
- [ ] Container

- Heudiconv version: 

version 0.5.4.dev1

**Comment by mgxd** [comment]
@yarikoptic your favorite bug is rearing its head again :wink:

**Comment by yarikoptic** [comment]
eh, I would not call it "favorite" - eventually we should abandon my ad-hoc desire for "beauty" ;-)
@greydongilmore sorry about that.  Could you rerun your conversion while adding `--dbg` option, and then when it ends up in `pdb` for debugging, enter "up", and then "p filename" and share with me/us that file (possibly removing any sensitive information if any, although that one could be the culprit here).

in the long run probably we should just RF to just not bother with the ad-hoc beautification of the json if that fails and just keep original and issue a warning ... I will submit a PR for that
