### ISSUE TITLE
Confusing/misleading message when trying to override subject id

### ISSUE THREAD

**Issue by yarikoptic** [nipy/heudiconv#355]
```shell
$ heudiconv -f XXX_reproin.py -s sid000861 --ses 1 --files  .../A002222  # session=None, subject='sid000861')
INFO: Running heudiconv version 0.5.4
INFO: Analyzing 3924 dicoms
INFO: Filtering out 0 dicoms based on their filename
/usr/lib/python2.7/dist-packages/heudiconv/dicoms.py:58: UserWarning: The DICOM readers are highly experimental, unstable, and only work for Siemens time-series at the moment
Please use with caution.  We would be grateful for your help in improving them
  import nibabel.nicom.dicomwrappers as dw
INFO: Generated sequence info for 2 studies with 23 entries total
Traceback (most recent call last):
  File "/usr/bin/heudiconv", line 11, in <module>
    load_entry_point('heudiconv==0.5.4', 'console_scripts', 'heudiconv')()
  File "/usr/lib/python2.7/dist-packages/heudiconv/cli/run.py", line 127, in main
    process_args(args)
  File "/usr/lib/python2.7/dist-packages/heudiconv/cli/run.py", line 260, in process_args
    args.subjs, grouping=args.grouping)
  File "/usr/lib/python2.7/dist-packages/heudiconv/parser.py", line 176, in get_study_sessions
    "found %d sequences" % (sids, len(sids), len(seqinfo_dict))
RuntimeError: We were provided some subjects (['sid000861']) but we can deal only with overriding only 1 subject id. Got 1 subjects and found 2 sequences
```
so is it a matter of overriding only in a single sequence? since it is only a single subject id.  So some logic might need to get fixed or extended

**Comment by mgxd** [comment]
It seems like this was the intended logic, but I've found this check to be more annoying than helpful
