### ISSUE TITLE
JSON/File not found when populating template files

### ISSUE THREAD

**Issue by utooley** [nipy/heudiconv#362]
### Summary
Converting ~600 subjs sometimes ends fine, sometimes ends with either a JSON decoder error, input/output error, or not finding `FileNotFoundError: [Errno 2] No such file or directory: '/mnt/niftis/task-rest_bold.json'`.

Things seem to be fine afterwards, dataset is bids-valid, but not sure what's up. Wondering whether it's a memory issue related to #356 or something like #311. I'm using 6 GBs, which has previously been enough, but maybe not anymore?

### Platform details:
- [ ] Container
heudiconv0.5.4.simg
dcm2niiX version v1.0.20190410  

Errors:

```
	 [Node] Finished "embedder".
INFO: [Node] Finished "embedder".
INFO: Post-treating /mnt/niftis/sub-NDARINVTW72EVWM/fmap/sub-NDARINVTW72EVWM_acq-fMRI_dir-AP_run-12_epi.json file
INFO: Populating template files under /mnt/niftis/
Traceback (most recent call last):
  File "/opt/miniconda-latest/bin/heudiconv", line 11, in <module>
    load_entry_point('heudiconv', 'console_scripts', 'heudiconv')()
  File "/src/heudiconv/heudiconv/cli/run.py", line 127, in main
    process_args(args)
  File "/src/heudiconv/heudiconv/cli/run.py", line 323, in process_args
    dcmconfig=args.dcmconfig,)
  File "/src/heudiconv/heudiconv/convert.py", line 212, in prep_conversion
    getattr(heuristic, 'DEFAULT_FIELDS', {}))
  File "/src/heudiconv/heudiconv/bids.py", line 77, in populate_bids_templates
    populate_aggregated_jsons(path)
  File "/src/heudiconv/heudiconv/bids.py", line 164, in populate_aggregated_jsons
    j = load_json(task_file)
  File "/src/heudiconv/heudiconv/utils.py", line 176, in load_json
    data = json.load(fp)
  File "/opt/miniconda-latest/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/opt/miniconda-latest/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/opt/miniconda-latest/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/miniconda-latest/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
or 
```
INFO: Populating template files under /mnt/niftis/
Traceback (most recent call last):
  File "/opt/miniconda-latest/bin/heudiconv", line 11, in <module>
    load_entry_point('heudiconv', 'console_scripts', 'heudiconv')()
  File "/src/heudiconv/heudiconv/cli/run.py", line 127, in main
    process_args(args)
  File "/src/heudiconv/heudiconv/cli/run.py", line 323, in process_args
    dcmconfig=args.dcmconfig,)
  File "/src/heudiconv/heudiconv/convert.py", line 212, in prep_conversion
    getattr(heuristic, 'DEFAULT_FIELDS', {}))
  File "/src/heudiconv/heudiconv/bids.py", line 77, in populate_bids_templates
    populate_aggregated_jsons(path)
  File "/src/heudiconv/heudiconv/bids.py", line 174, in populate_aggregated_jsons
    save_json(task_file, fields, indent=2, sort_keys=True, pretty=True)
  File "/src/heudiconv/heudiconv/utils.py", line 200, in save_json
    assure_no_file_exists(filename)
  File "/src/heudiconv/heudiconv/utils.py", line 183, in assure_no_file_exists
    os.unlink(path)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/niftis/task-rest_bold.json'
```
or 
```
INFO: Populating template files under /mnt/niftis/
Traceback (most recent call last):
  File "/opt/miniconda-latest/bin/heudiconv", line 11, in <module>
    load_entry_point('heudiconv', 'console_scripts', 'heudiconv')()
  File "/src/heudiconv/heudiconv/cli/run.py", line 127, in main
    process_args(args)
  File "/src/heudiconv/heudiconv/cli/run.py", line 323, in process_args
    dcmconfig=args.dcmconfig,)
  File "/src/heudiconv/heudiconv/convert.py", line 212, in prep_conversion
    getattr(heuristic, 'DEFAULT_FIELDS', {}))
  File "/src/heudiconv/heudiconv/bids.py", line 77, in populate_bids_templates
    populate_aggregated_jsons(path)
  File "/src/heudiconv/heudiconv/bids.py", line 164, in populate_aggregated_jsons
    j = load_json(task_file)
  File "/src/heudiconv/heudiconv/utils.py", line 176, in load_json
    data = json.load(fp)
  File "/opt/miniconda-latest/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
OSError: [Errno 5] Input/output error
```

[heuristic_ABCD 1.txt](https://github.com/nipy/heudiconv/files/3436922/heuristic_ABCD.1.txt)

**Comment by mgxd** [comment]
@utooley are you running multiple participants in parallel? If so, it may be related to the race-condition of creating the top-level JSON files discussed in #340

**Comment by utooley** [comment]
Ahh, yes, I see! I am indeed running multiple participants in parallel, sorry I didn't dig through the issues more carefully to find a more plausible culprit. In that case, then, it seems that everything is okay afterwards if the dataset is still BIDS-valid--correct me if I'm wrong.

**Comment by AKSoo** [comment]
I have also encountered this error while running multiple instances of heudiconv in parallel, and the error threw off the post conversion processing script.

Unless #348 will get merged soon, we should add a small note in the usage docs.

**Comment by yarikoptic** [comment]
well, #348 was merged and #516 seems to be a different issue.  I will close this one, but if someone runs into it again (e.g. the locking of #348 is not good enough for distributed FS or smth like that) -- chime in and we will reopen it.

**Comment by burdinskid13** [comment]
Hi there, I am running into the same issue as the original poster. I am not sure how I should manipulate the heudiconv lock in order to resolve this for myself. Could you please help @yarikoptic or @mgxd?

**Comment by yarikoptic** [comment]
@burdinskid13 just to make sure -- you are using 0.9.0 heudiconv or 0.5.4 as original poster?

**Comment by burdinskid13** [comment]
I am using 0.9.0 heudiconv!
