### ISSUE TITLE
"no module named heudiconv" from docker

### ISSUE THREAD

**Issue by jokedurnez** [nipy/heudiconv#37]
I tried running heudiconv from the docker container pulled frum dockerhub.  This is the error I get:

```
INFO: Processing 3556 dicoms
Traceback (most recent call last):
  File "/usr/local/bin/heudiconv", line 849, in <module>
    main()
  File "/usr/local/bin/heudiconv", line 845, in main
    is_bids=args.bids)

  File "/usr/local/bin/heudiconv", line 682, in convert_dicoms
    mod = __import__(fname.split('.')[0])
ImportError: No module named heudiconv

```

**Comment by jokedurnez** [comment]
NVM, the extension of my heuristics-file was not .py...
