### ISSUE TITLE
Conda install broken 

### ISSUE THREAD

**Issue by jacobtfisher** [nipy/heudiconv#426]
### Summary

It seems that installing `heudiconv` with `conda` no longer works. I've tried with a fresh environment, with python 3.6 and 3.7, and both a Mac and an Ubuntu (18.04) system. It first fails saying that there are incompatible packages, but then cannot find the conflicting packages. 

This is the error message: 

```
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/cli/install.py", line 265, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 275, in solve_final_state
        ssc = self._add_specs(ssc)
      File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 696, in _add_specs
        raise UnsatisfiableError({})
    conda.exceptions.UnsatisfiableError:
    Did not find conflicting dependencies. If you would like to know which
    packages conflict ensure that you have enabled unsatisfiable hints.

    conda config --set unsatisfiable_hints True


    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        return getattr(module, func_name)(args, parser)
      File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/cli/install.py", line 299, in install
        should_retry_solve=(repodata_fn != repodata_fns[-1]),
      File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 275, in solve_final_state
        ssc = self._add_specs(ssc)
      File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 694, in _add_specs
        ssc.r.find_conflicts(spec_set)
      File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/resolve.py", line 347, in find_conflicts
        bad_deps = self.build_conflict_map(specs, specs_to_add, history_specs)
      File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/resolve.py", line 507, in build_conflict_map
        root, search_node, dep_graph, num_occurances)
      File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/resolve.py", line 369, in breadth_first_search_for_dep_graph
        last_spec = MatchSpec.union((path[-1], target_paths[-1][-1]))[0]
      File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 481, in union
        return cls.merge(match_specs, union=True)
      File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 475, in merge
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 475, in <lambda>
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 502, in _merge
        final = this_component.union(that_component)
      File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 764, in union
        return '|'.join(options)
    TypeError: sequence item 0: expected str instance, Channel found

`$ /usr/local/anaconda3/bin/conda install -c conda-forge heudiconv`

  environment variables:
                 ANTSPATH=/usr/local/antsbin/bin/
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=test
                CONDA_EXE=/usr/local/anaconda3/bin/conda
             CONDA_PREFIX=/home/jtf/.conda/envs/test
           CONDA_PREFIX_1=/usr/local/anaconda3
    CONDA_PROMPT_MODIFIER=(test)
         CONDA_PYTHON_EXE=/usr/local/anaconda3/bin/python
               CONDA_ROOT=/usr/local/anaconda3
              CONDA_SHLVL=2
          LD_LIBRARY_PATH=/usr/lib/fsl/5.0:/usr/share/fsl/5.0/FSLeyes
             MNI_DATAPATH=/usr/local/freesurfer/mni/data
               MODULEPATH=/etc/environment-modules/modules:/usr/share/modules/versions:/usr/shar
                          e/modules/$MODULE_VERSION/modulefiles:/usr/share/modules/modulefiles
                     PATH=/usr/local/anaconda3/bin:/usr/local/fsl/bin:/home/jtf/bin:/home/jtf/.l
                          ocal/bin:/home/jtf/.conda/envs/test/bin:/usr/local/anaconda3/condabin:
                          /usr/local/IBM/SPSS/Statistics/25/bin:/usr/local/gephi-0.9.2/bin:/usr/
                          local/antsbin/bin:/usr/local/freesurfer/bin:/usr/local/freesurfer/fsfa
                          st/bin:/usr/local/freesurfer/tktools:/usr/share/fsl/5.0/bin:/usr/lib/f
                          sl/5.0:/usr/local/freesurfer/mni/bin:/usr/share/fsl/5.0/bin:/usr/local
                          /sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/loc
                          al/games:/snap/bin:/home/jtf/.dotnet/tools
          PKG_CONFIG_PATH=/usr/lib/pkgconfig
       REQUESTS_CA_BUNDLE=<not set>
                 SPM_PATH=/usr/local/MATLAB/R2017b/toolbox/spm12/
            SSL_CERT_FILE=<not set>

     active environment : test
    active env location : /home/jtf/.conda/envs/test
            shell level : 2
       user config file : /home/jtf/.condarc
 populated config files : /home/jtf/.condarc
          conda version : 4.8.2
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       virtual packages : __cuda=10.2
                          __glibc=2.27
       base environment : /usr/local/anaconda3  (read only)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/anaconda3/pkgs
                          /home/jtf/.conda/pkgs
       envs directories : /home/jtf/.conda/envs
                          /usr/local/anaconda3/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.3 Linux/5.3.0-7625-generic ubuntu/18.04.4 glibc/2.27
                UID:GID : 10005:10004
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: y
Upload successful.
```
I have also tried downgrading to an older version of `conda` (4.6.14) to no avail. Any suggestions?

### Platform details:

Choose one:
- [x] Local environment

- [ ] Container

- Heudiconv version: `0.6.0`

**Comment by yarikoptic** [comment]
Thank you for the report!
oh well, conda is more sophisticated than poor pypi/pip, but also known for possible "impossible" installations or taking forever to figure out possible installation given dependency graph.

I will kick out 0.7.0 soon and then will try (after update pkg in conda).  Meanwhile `pip install heudiconv` might still work . On ubuntu 18.04 -- we provide it from neurodebian: http://neuro.debian.net/pkgs/heudiconv.html  so that is the easiest installation path there ;-)

**Comment by jacobtfisher** [comment]
We were able to get it working with `pip` for now. I'll check back when `0.7.0` is released to see if the conda install is working again. Thank you!

**Comment by mick-d** [comment]
Just to follow up on this, i could install `heudiconv` fine with `conda` (`4.8.3`) on Ubuntu 20.04 in a python 3.7 env, but not in a python 3.8 env. In both cases conda channels were by order of priority: `conda-forge`, `defaults`. This fails in a brand new python 3.8 env.

<details> 
<summary> <code> conda create -n heuditest python=3.8 </code></summary>

```
conda create -n heuditest python=3.8
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/conda/shared/envs/heuditest

  added / updated specs:
    - python=3.8


The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-0_gnu
  ca-certificates    conda-forge/linux-64::ca-certificates-2020.4.5.1-hecc5488_0
  certifi            conda-forge/linux-64::certifi-2020.4.5.1-py38h32f6830_0
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.34-h53a641e_0
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1007
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.2.0-h24d8f2e_2
  libgomp            conda-forge/linux-64::libgomp-9.2.0-h24d8f2e_2
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.2.0-hdf63c60_2
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  openssl            conda-forge/linux-64::openssl-1.1.1g-h516909a_0
  pip                conda-forge/noarch::pip-20.1-pyh9f0ad1d_0
  python             conda-forge/linux-64::python-3.8.2-he5300dc_7_cpython
  python_abi         conda-forge/linux-64::python_abi-3.8-1_cp38
  readline           conda-forge/linux-64::readline-8.0-hf8c457e_0
  setuptools         conda-forge/linux-64::setuptools-46.2.0-py38h32f6830_0
  sqlite             conda-forge/linux-64::sqlite-3.30.1-hcee41ef_0
  tk                 conda-forge/linux-64::tk-8.6.10-hed695b0_0
  wheel              conda-forge/noarch::wheel-0.34.2-py_1
  xz                 conda-forge/linux-64::xz-5.2.5-h516909a_0
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1006


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate heuditest
#
# To deactivate an active environment, use
#
#     $ conda deactivate

```
</details>

Now installing `heudiconv`:
```
$ conda install -n heuditest heudiconv
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==10.2=0
  - feature:|@/linux-64::__cuda==10.2=0

Your installed CUDA driver is: 10.2
```

A similar issue seems to happen when installing other packages, e.g. c.f. conda-forge/spyder-feedstock/issues/72 and KevinMusgrave/pytorch-metric-learning/issues/55 although i could only reproduce the same issue with the latter. When looking at the common packages between `heudiconv` and `pytorch-metric-learning` which would be installed in a python 3.7 env (`cffi freetype jpeg libgfortran-ng libpng libtiff libwebp-base lz4-c numpy scipy pycparser six zstd`), installing all of these together in the python 3.8 env was fine however (no errors).
