### ISSUE TITLE
ImportError: No module named configparser

### ISSUE THREAD

**Issue by chpiero** [nipy/heudiconv#44]
When try to run ( i've installed "heudiconv docker" from [https://hub.docker.com/r/nipy/heudiconv/]() )

`docker run --rm -it -v $PWD:/data nipy/heudiconv -d /data/%s/YAROSLAV_DBIC-TEST1/HEAD_ADVANCED_APPLICATIONS_LIBRARIES_20160824_104430_780000/*/*IMA -s PHANTOM1_3 -f /data/convertall.py -c dcm2niix -b -o /data/output`

 i've this error:

`INFO: Processing 128 dicoms
Traceback (most recent call last):
  File "/usr/local/bin/heudiconv", line 849, in <module>
    main()
  File "/usr/local/bin/heudiconv", line 845, in main
    is_bids=args.bids)
  File "/usr/local/bin/heudiconv", line 731, in convert_dicoms
    sourcedir=sourcedir)
  File "/usr/local/bin/heudiconv", line 461, in convert
    from nipype import Function, Node
  File "/opt/conda/lib/python2.7/site-packages/nipype/__init__.py", line 11, in <module>
    from .utils.config import NipypeConfig
  File "/opt/conda/lib/python2.7/site-packages/nipype/utils/config.py", line 15, in <module>
    import configparser
ImportError: No module named configparser`

thanks,

Piero

**Comment by satra** [comment]
@chpiero - give it a few minutes for the dockerfile to build on docker hub and then pull the latest.
