### ISSUE TITLE
datalad integration error: dataset containing given paths is not underneath the reference dataset

### ISSUE THREAD

**Issue by DVSneuro** [nipy/heudiconv#456]
### Summary

Hi -- I'm using the datalad integration with heudiconv, but I'm encountering a `dataset containing given paths is not underneath the reference dataset` error, which has also been flagged as an issue on the datalad issues page (https://github.com/datalad/datalad/issues/3928). Some example code and the full output is below, but I'm first creating a superdataset and a subdataset named bids and then using heudiconv to write output into that bids subdataset. It looks like I'm missing something the reference dataset, which I thought would've been inherited from the superdataset. 

I suspect I'm just going about this in the wrong way, so feedback is welcome and appreciated.

Thanks!
David

Example code:
```
# make superdataset and connect to remotes
datalad create --description "data on Computer A" -c text2git mysuperdataset
cd mysuperdataset
git annex initremote gdrive type=external externaltype=rclone target=mygdrive prefix= mysuperdataset/annex chunk=50MiB encryption=none rclone_layout=lower
datalad create-sibling-github mysuperdataset -s github --publish-depends gdrive

# make bids subdataset
datalad create -d . -c text2git bids

# run heudiconv
sub=131
singularity run --cleanenv -B $dsroot:/out -B $sourcedata:/sourcedata \
/data/tools/heudiconv-0.8.0.simg -d /sourcedata/dicoms/SMITH-AgingDM-{subject}/*/DICOM/*.dcm -s $sub \
-f /out/code/heuristics.py -c dcm2niix -b --minmeta --datalad -o /out/bids
```

Resulting output:
```
	 [Node] Finished "convert".
INFO: [Node] Finished "convert".
INFO: Post-treating /out/bids/sub-131/func/sub-131_task-sharedreward_run-02_bold.json file
INFO: Lock 140068337472512 acquired on /out/bids/heudiconv.lock
INFO: Populating template files under /out/bids/
INFO: Lock 140068337472512 released on /out/bids/heudiconv.lock
INFO: PROCESSING DONE: {'subject': '131', 'outdir': '/out/bids/', 'session': None}
[ERROR  ] dataset containing given paths is not underneath the reference dataset <Dataset path=/out/bids>: [PosixPath('/out/bids')] [status(/out)] 
ERROR  : dataset containing given paths is not underneath the reference dataset <Dataset path=/out/bids>: [PosixPath('/out/bids')] [status(/out)]
Traceback (most recent call last):
  File "/opt/miniconda-latest/bin/heudiconv", line 11, in <module>
    load_entry_point('heudiconv', 'console_scripts', 'heudiconv')()
  File "/src/heudiconv/heudiconv/cli/run.py", line 134, in main
    process_args(args)
  File "/src/heudiconv/heudiconv/cli/run.py", line 365, in process_args
    add_to_datalad(outdir, study_outdir, msg, args.bids_options)
  File "/src/heudiconv/heudiconv/external/dlad.py", line 141, in add_to_datalad
    superds.save(path=ds.path, message=msg, recursive=True)
  File "/opt/miniconda-latest/lib/python3.6/site-packages/datalad/distribution/dataset.py", line 500, in apply_func
    return f(**kwargs)
  File "/opt/miniconda-latest/lib/python3.6/site-packages/datalad/interface/utils.py", line 492, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/opt/miniconda-latest/lib/python3.6/site-packages/datalad/interface/utils.py", line 480, in return_func
    results = list(results)
  File "/opt/miniconda-latest/lib/python3.6/site-packages/datalad/interface/utils.py", line 467, in generator_func
    msg="Command did not complete successfully")
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully [{'path': '/out', 'refds': '/out/bids', 'action': 'status', 'status': 'error', 'message': ('dataset containing given paths is not underneath the reference dataset %s: %s', <Dataset path=/out/bids>, [PosixPath('/out/bids')])}]
```

### Platform details:

Choose one:
- [ ] Local environment

- [x] Container: Singularity

- Heudiconv version: 0.8.0

**Comment by yarikoptic** [comment]
I guess dsroot is also pointing to a dataset or a git repo. We need to fix up to not go up higher than the path specified in -o. 
In general though, you might want to consider using datalad run or containers-run and abandon --datalad functionality of heudiconv - it was introduced before we formalized Yoda principles , see eg https://github.com/ReproNim/containers/blob/master/README.md#repronimcontainers---containerized-environments-for-reproducible-neuroimaging for more info

**Comment by yarikoptic** [comment]
datalad-neuroimaging BTW provides cfg_bids so you could use `datalad create -c bids` for basic initial configuration for a bids dataset (more to be done there though)

**Comment by DVSneuro** [comment]
Thanks for the suggestion! We'll drop the `--datalad` from huediconv and work through `datalad run` instead. 

I've had some problems/questions with `datalad run`, but that's beyond the scope of the issue here, so I just [posted to NeuroStars](https://neurostars.org/t/dealing-with-locked-files-with-datalad-run/6980) to keep things more organized and clear (hopefully).
