### ISSUE TITLE
ValueError: No JSON object could be decoded (when running w/ --bids)

### ISSUE THREAD

**Issue by danlurie** [nipy/heudiconv#51]
When trying to run `heudiconv` with the `--bids` flag (to try to get it to use sub-<id> for subject folders), I get the following error:

```
(legacy) # dlurie@nx4 in /home/despoB/lesion/data/original/bids_test [12:57:59]
$ heudiconv -d /home/despoB/lesion/data/original/dicom/%s/*/* -s 101 -f /home/despoB/dlurie/Software/heudiconv/heuristics/uc_bids.py -c dcm2niix -o nifti_new -b
INFO: Processing 539 dicoms
INFO: Generated sequence info with 20 entries
INFO: Doing conversion using dcm2niix
Converting /home/despoB/lesion/data/original/bids_test/nifti_new/sub-101/func/sub-101_task-rest_acq-128px_run-01_bold
/home/despoB/lesion/data/original/bids_test/nifti_new/sub-101/func
INFO: Processing 300 dicoms
dcm2niix
INFO: Executing node convert in dir: /tmp/heudiconvtmpWwNvTv/convert
INFO: Running: dcm2niix -b y -z i -x n -t n -m n -f func_%e -o /scratch/tmp/heudiconvtmpWwNvTv/convert -s n -v n /scratch/tmp/heudiconvtmpWwNvTv/convert/IM-0009-0001.dcm
Traceback (most recent call last):
  File "/home/despoB/dlurie/Software/heudiconv/bin/heudiconv", line 884, in <module>
    main()
  File "/home/despoB/dlurie/Software/heudiconv/bin/heudiconv", line 880, in main
    min_meta=args.minmeta)
  File "/home/despoB/dlurie/Software/heudiconv/bin/heudiconv", line 761, in convert_dicoms
    min_meta=min_meta)
  File "/home/despoB/dlurie/Software/heudiconv/bin/heudiconv", line 550, in convert
    embedfunc.inputs.bids_info = load_json(os.path.abspath(scaninfo))
  File "/home/despoB/dlurie/Software/heudiconv/bin/heudiconv", line 92, in load_json
    data = json.load(fp)
  File "/home/despoB/dlurie/anaconda3/envs/legacy/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/home/despoB/dlurie/anaconda3/envs/legacy/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/home/despoB/dlurie/anaconda3/envs/legacy/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/despoB/dlurie/anaconda3/envs/legacy/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```
The heuristic I'm using can be [found here](https://github.com/danlurie/heudiconv/blob/master/heuristics/uc_bids.py).

It looks like `heudiconv` makes it through conversion for the first image and then crashes. Here's what it what gets written out prior to crashing:
```
nifti_new/:
sub-101/

nifti_new/sub-101:
func/
info/

nifti_new/sub-101/func:
sub-101_task-rest_acq-128px_run-01_bold.json
sub-101_task-rest_acq-128px_run-01_bold.nii.gz

nifti_new/sub-101/info:
101.auto.txt
101.edit.txt
dicominfo.txt
filegroup.json
uc_bids.py
```
Everything looks normal in `101.auto.txt`, so it seems to be picking up the other scans okay. The scan-parameters JSON file also looks good.

If I run the same command without the `--bids` flag, everything converts without an error.

I've tried to look through the code to get an idea of what is going wrong,  but I can't figure out what exactly is going on with `scaninfo` (i.e. what it's supposed to contain, when it's supposed to be created, etc).

Any ideas? Thanks!

**Comment by danlurie** [comment]
Turns out this issue was caused by using an old version of dcm2niix. Building from source downloaded from the latest GitHub release fixed the problem.
