### ISSUE TITLE
scans.tsv created then removed during conversion, prompting FileNotFoundError

### ISSUE THREAD

**Issue by andrew-yian-sun** [nipy/heudiconv#536]
### Summary

I am running the conversion step of heudiconv. This conversion has worked for a previous participant. In subsequent participants, however, it stops sometime during the conversion. Strangely, I can see that a scans.tsv file is created, but then it is removed, therefore prompting a FileNotFoundError. 

Here is the command I ran:
``` Bash
docker run --rm --privileged --interactive \
--volume /Volumes/NIA_R21/data_mri:/base nipy/heudiconv:latest \
--dicom_dir_template /base/dataOLD/s{subject}/raw_session{session}/*/*.IMA \
--outdir /base/dataOLD_BIDS_test/ \
--heuristic /base/heudiconv/heuristic_ses-1.py \
--subjects 0117 \
--ses 1 \
--converter dcm2niix \
--bids \
--overwrite
```

Here is the heuristic I used:
``` Python
import os
def create_key(template, outtype=('nii.gz',), annotation_classes=None):
    if template is None or not template:
        raise ValueError('Template must be a valid format string')
    return template, outtype, annotation_classes
def infotodict(seqinfo):
    """    
    t1w = create_key('sub-{subject}/{session}/anat/sub-{subject}_{session}_T1w')
    t2w = create_key('sub-{subject}/{session}/anat/sub-{subject}_{session}_T2w')
    dwi_b500_AP = create_key('sub-{subject}/{session}/dwi/sub-{subject}_{session}_acq-b500_dir-AP_run-{item:03d}_dwi')
    dwi_b2000_AP = create_key('sub-{subject}/{session}/dwi/sub-{subject}_{session}_acq-b2000_dir-AP_run-{item:03d}_dwi')
    epi_b0_PA = create_key('sub-{subject}/{session}/fmap/sub-{subject}_{session}_acq-b0_dir-PA_dwi')
    chimap = create_key('sub-{subject}/{session}/fmap/sub-{subject}_{session}_run-{item:03d}_Chimap')

    info = {t1w: [], t2w: [], dwi_b500_AP: [], dwi_b2000_AP: [], epi_b0_PA: [], chimap: []}

    for s in seqinfo:
        if 't1_mprage' in s.protocol_name:
            info[t1w].append(s.series_id)
        if 'T2w_SPC' in s.protocol_name:
            info[t2w].append(s.series_id)
        if 'diff_0.95mm_AP_b500_Scan' in s.protocol_name:
            info[dwi_b500_AP].append(s.series_id)
        if 'diff_0.95mm_AP_b2000_Scan' in s.protocol_name:
            info[dwi_b2000_AP].append(s.series_id)
        if 'diff_0.95mm_PA_b0' in s.protocol_name:
            info[epi_b0_PA].append(s.series_id)
        if 'GRE_QSM' in s.protocol_name:
            info[chimap].append(s.series_id)
    return info
```
Conversion log is quite long, so here are the last couple of lines:

```INFO: [Node] Finished "convert".
Traceback (most recent call last):
  File "/opt/miniconda-latest/bin/heudiconv", line 33, in <module>
    sys.exit(load_entry_point('heudiconv', 'console_scripts', 'heudiconv')())
  File "/src/heudiconv/heudiconv/cli/run.py", line 24, in main
    workflow(**kwargs)
  File "/src/heudiconv/heudiconv/main.py", line 351, in workflow
    grouping=grouping,)
  File "/src/heudiconv/heudiconv/convert.py", line 216, in prep_conversion
    dcmconfig=dcmconfig,)
  File "/src/heudiconv/heudiconv/convert.py", line 486, in convert
    save_scans_key(item, bids_outfiles)
  File "/src/heudiconv/heudiconv/bids.py", line 346, in save_scans_key
    op.join(output_dir, 'sub-{0}{1}_scans.tsv'.format(subj, ses)), rows)
  File "/src/heudiconv/heudiconv/bids.py", line 391, in add_rows_to_scans_keys_file
    with open(fn, 'a') as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: '/base/dataOLD_BIDS_test/sub-0117/ses-1/sub-0117_ses-1_scans.tsv'
```

### Platform details:

Choose one:
- [ ] Local environment

- [x] Container

- Docker Desktop version: 4.2.0
- Heudiconv version: 0.9.0

**Comment by yarikoptic** [comment]
does that folder exists (mounted inside container)?

`'a'` should create file if it exists. Error though is a bit "misleading" since really it shouldn't matter if file exists -- it fails if folder doesn't:

```
(git)lena:~/picts/mris/heudiconv-master[master]git
$> python3 -c "open('/tmp/nonexisting', 'a').write('blah')"

$> python3 -c "open('/tmp/absentfolder/nonexisting', 'a').write('blah')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/absentfolder/nonexisting'
```

indeed that function first reads/removes the file if it exists and then rewrites with new information (not sure why we use `'a'` and not just `'w'` ATM, may be legacy)

**Comment by andrew-yian-sun** [comment]
Which folder are you asking about specifically? Do you mean the outdir path? I ran the following: 
```
docker run --rm --privileged --interactive \
--volume /Volumes/NIA_R21/data_mri:/base \
--entrypoint=bash \
nipy/heudiconv:latest
```
then `ls base` inside the container does show `dataOLD_BIDS_test`

Let me know what I should check.

**Comment by andrew-yian-sun** [comment]
If you mean `/base/dataOLD_BIDS_test/sub-0117/ses-1/`, yes, that does exist.

**Comment by yarikoptic** [comment]
I am still lost at what might be going on. I believe there is --pdb option - add it and you should end up in pdb debugger when that exception happens. Try to call that open, or somehow otherwise investigate what might be going on. Add your said other subjects were ok? It is was just one subject ok, and the 2nd fails?

**Comment by andrew-yian-sun** [comment]
Strangely, I tried the same exact code today and it seem to have worked. No idea why.
