### ISSUE TITLE
ERROR: Embedding failed

### ISSUE THREAD

**Issue by ibrwr** [nipy/heudiconv#539]
### Summary

Hi all,

My conversion seem to go well, i get nifti and populated json files. But very often I get the error "ERROR: Embedding failed: Exception raised while executing Node embedder." 

Do I understand correctly that this is dcmstack crashing on some values it found in the dicom file and therefore the only result is that some extra information is missing in the json file but to solve it, it would need to be fixed in dcmstack?

Thanks for help!

Iman

### Platform details:

Choose one:
- [x] Local environment: version 10.0 on python 3.6.8 on Rad Hat Linux

- [ x] Container 9.0.0

- Heudiconv version: dependent on environment, see above

211210-13:05:33,955 nipype.workflow INFO:
         [Node] Setting-up "embedder" in "/tmp/embedmetapm5_9hl7/embedder".
INFO: [Node] Setting-up "embedder" in "/tmp/embedmetapm5_9hl7/embedder".
211210-13:05:33,960 nipype.workflow INFO:
         [Node] Executing "embedder" <nipype.interfaces.utility.wrappers.Function>
INFO: [Node] Executing "embedder" <nipype.interfaces.utility.wrappers.Function>
211210-13:05:33,971 nipype.workflow INFO:
         [Node] Finished "embedder", elapsed time 0.010596s.
INFO: [Node] Finished "embedder", elapsed time 0.010596s.
211210-13:05:33,971 nipype.workflow WARNING:
         Storing result file without outputs
WARNING: Storing result file without outputs
211210-13:05:33,972 nipype.workflow WARNING:
         [Node] Error on "embedder" (/tmp/embedmetapm5_9hl7/embedder)
WARNING: [Node] Error on "embedder" (/tmp/embedmetapm5_9hl7/embedder)
ERROR: Embedding failed: Exception raised while executing Node embedder.

Traceback (most recent call last):
  File "/<shortened_path>/heudiconv_venv_10.0/lib64/python3.6/site-packages/nipype/interfaces/base/core.py", line 398, in run
    runtime = self._run_interface(runtime)
  File "/<shortened_path>/heudiconv_venv_10.0/lib64/python3.6/site-packages/nipype/interfaces/utility/wrappers.py", line 142, in _run_interface
    out = function_handle(**args)
  File "<string>", line 28, in embed_dicom_and_nifti_metadata
  File "/<shortened_path>/heudiconv_venv_10.0/lib64/python3.6/site-packages/dcmstack/dcmstack.py", line 1223, in parse_and_stack
    warn_on_except)
  File "/<shortened_path>/heudiconv_venv_10.0/lib64/python3.6/site-packages/dcmstack/dcmstack.py", line 1126, in parse_and_group
    meta = extractor(dcm)
  File "/<shortened_path>/heudiconv_venv_10.0/lib64/python3.6/site-packages/dcmstack/extract.py", line 504, in __call__
    value = self._get_elem_value(elem)
  File "/<shortened_path>/heudiconv_venv_10.0/lib64/python3.6/site-packages/dcmstack/extract.py", line 423, in _get_elem_value
    value = [self.conversions[elem.VR](val) for val in value]
TypeError: 'NoneType' object is not iterable

**Comment by marlietandoc** [comment]
Did you ever end up figuring out if this was a problem? I get the exact same error.

**Comment by yarikoptic** [comment]
there might have been some fixes in dcmstack since then e.g. https://github.com/moloney/dcmstack/pull/76 .  What is the version of dcmstack you have @marlietandoc - do you know?  if before 0.9 -- could you try with 0.9?

**Comment by marlietandoc** [comment]
@yarikoptic Thanks for looking into this.  I am using the most up-to-date version of heudiconv (version 0.11.6, running it as a singularity container) I'm trying to verify now what version of dcmstack it is using, but assume its most up to date one?

The exact error I get (for every .json file/scan that Heudiconv tries to create, so its happening every time for all subjects)  is as follows:   Node] Error on "embedder" (/tmp/embedmetaxgkuj2qa/embedder)
WARNING: [Node] Error on "embedder" (/tmp/embedmetaxgkuj2qa/embedder)
ERROR: Embedding failed: Exception raised while executing Node embedder.

Traceback (most recent call last):
  File "/opt/miniconda-latest/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 398, in run
    runtime = self._run_interface(runtime)
  File "/opt/miniconda-latest/lib/python3.7/site-packages/nipype/interfaces/utility/wrappers.py", line 142, in _run_interface
    out = function_handle(**args)
  File "<string>", line 28, in embed_dicom_and_nifti_metadata
  File "/opt/miniconda-latest/lib/python3.7/site-packages/dcmstack/dcmstack.py", line 1223, in parse_and_stack
    warn_on_except)
  File "/opt/miniconda-latest/lib/python3.7/site-packages/dcmstack/dcmstack.py", line 1126, in parse_and_group
    meta = extractor(dcm)
  File "/opt/miniconda-latest/lib/python3.7/site-packages/dcmstack/extract.py", line 504, in __call__
    value = self._get_elem_value(elem)
  File "/opt/miniconda-latest/lib/python3.7/site-packages/dcmstack/extract.py", line 423, in _get_elem_value
    value = [self.conversions[elem.VR](val) for val in value]
TypeError: 'NoneType' object is not iterable

**Comment by bpinsard** [comment]
Got the same error on GE data.
Might be caused by an anonymization tool.

see https://github.com/moloney/dcmstack/pull/93 for potential fix.
