### ISSUE TITLE
TraitError: Each element of the 'source_names' trait of a Dcm2niixInputSpec instance must be a pathlike object or string representing an existing file

### ISSUE THREAD

**Issue by crcox** [nipy/heudiconv#550]
### Platform details:

Choose one:
- [ ] Local environment

- [x] Container

docker.io/nipy/heudiconv                      latest      afdef7270c0e

- Heudiconv version: 0.9.0

I do not understand this error, why it's happening, or where to turn to debug it. All my files are named `/data/crcox/Ser4/meEPI_i6[0-9]+.MRDC.[0-9]+`, where the `[0-9]+` just means one or more digits. You can see in the error that it is looking for a file without the `meEPI_` prefix. I get the same error more quickly if I try to use the `--dicom_dir_template`.

Command:

```
podman run \
  --rm \
  --user root \
  --volume ${PWD}/DICOM/:/data:Z \
  --volume ${PWD}/Nifti/:/output:Z \
  --tmpfs=/run \
  --tmpfs=/tmp \
  docker.io/nipy/heudiconv:latest \
    --files \
      /data/crcox/Ser3 \
      /data/crcox/Ser4 \
    --subjects "crcox" \
    --outdir /output \
    --heuristic /output/code/heuristic.py \
    --converter dcm2niix \
    --overwrite \
    --bids
```

Heuristic:
```
[chriscox@relearn0 code]$ cat heuristic.py
import os

def create_key(template, outtype=('nii.gz',), annotation_classes=None):
    if template is None or not template:
        raise ValueError('Template must be a valid format string')
    return template, outtype, annotation_classes


def infotodict(seqinfo):
    """Heuristic evaluator for determining which runs belong where

    allowed template fields - follow python string module:

    item: index within category
    subject: participant id
    seqitem: run number during scanning
    subindex: sub index within group
    """

    t1w = create_key('sub-{subject}/anat/sub-{subject}_run-{item:02d}_acq-32ch_T1w')
    # sub-<label>[_ses-<label>]_task-<label>[_acq-<label>][_ce-<label>][_rec-<label>][_dir-<label>][_run-<index>][_echo-<index>][_part-<mag|phase|real|imag>]_bold.nii[.gz]
    func_task_echo1 = create_key('sub-{subject}/func/sub-{subject}_task-triplet_acq-32ch_bold_run-{item:02d}_echo-1')
    func_task_echo2 = create_key('sub-{subject}/func/sub-{subject}_task-triplet_acq-32ch_bold_run-{item:02d}_echo-2')
    func_task_echo3 = create_key('sub-{subject}/func/sub-{subject}_task-triplet_acq-32ch_bold_run-{item:02d}_echo-3')

    info = {t1w: [], func_task: []}
    last_run = len(seqinfo)

    for s in seqinfo:
        """
        The namedtuple `s` contains the following fields:

        * total_files_till_now
        * example_dcm_file
        * series_id
        * dcm_dir_name
        * unspecified2
        * unspecified3
        * dim1
        * dim2
        * dim3
        * dim4
        * TR
        * TE
        * protocol_name
        * is_motion_corrected
        * is_derived
        * patient_id
        * study_description
        * referring_physician_name
        * series_description
        * image_type
        """

        if s.series_description == "SAG_MPRAGE":
            info[t1w].append(s.series_id)
        elif series_description == "epiRTmeasl" and int(TE) == 14:
            info[func_task_echo1].append(s.series_id)
        elif series_description == "epiRTmeasl" and int(TE) == 28:
            info[func_task_echo2].append(s.series_id)
        elif series_description == "epiRTmeasl" and int(TE) == 43:
            info[func_task_echo3].append(s.series_id)

    return info
```

Output:
```
[chriscox@relearn0 MRS_fMRI_16Feb2022_MultiEcho]$ ./02_dicom_to_bids.sh
INFO: Running heudiconv version 0.9.0 latest 0.10.0
INFO: Analyzing 13424 dicoms
INFO: Generated sequence info for 1 studies with 2 entries total
WARNING: Heuristic is missing an `infotoids` method, assigning empty method and using provided subject id crcox. Provide `session` and `locator` fields for best results.
INFO: Study session for StudySessionInfo(locator=None, session=None, subject='crcox')
INFO: Need to process 1 study sessions
INFO: PROCESSING STARTS: {'subject': 'crcox', 'outdir': '/output/', 'session': None}
INFO: Processing 2 pre-sorted seqinfo entries
INFO: Reloading existing filegroup.json because /output/.heudiconv/crcox/info/crcox.edit.txt exists
INFO: Doing conversion using dcm2niix
INFO: Converting /output/run001 (30 DICOMs) -> /output . Converter: dcm2niix . Output types: ('nii.gz',)
220328-21:22:01,683 nipype.utils WARNING:
         A newer version (1.7.0) of nipy/nipype is available. You are using 1.6.0
WARNING: A newer version (1.7.0) of nipy/nipype is available. You are using 1.6.0
220328-21:22:01,685 nipype.workflow INFO:
         [Node] Setting-up "convert" in "/tmp/dcm2niixgqigrzyl/convert".
INFO: [Node] Setting-up "convert" in "/tmp/dcm2niixgqigrzyl/convert".
220328-21:22:01,697 nipype.workflow INFO:
         [Node] Running "convert" ("nipype.interfaces.dcm2nii.Dcm2niix"), a CommandLine Interface with command:
dcm2niix -b y -z y -x n -t n -m n -f run001_heudiconv257 -o /output -s n -v n /tmp/dcm2niixgqigrzyl/convert
INFO: [Node] Running "convert" ("nipype.interfaces.dcm2nii.Dcm2niix"), a CommandLine Interface with command:
dcm2niix -b y -z y -x n -t n -m n -f run001_heudiconv257 -o /output -s n -v n /tmp/dcm2niixgqigrzyl/convert
220328-21:22:01,792 nipype.interface INFO:
         stdout 2022-03-28T21:22:01.792619:Chris Rorden's dcm2niiX version v1.0.20190410  GCC6.3.0 (64-bit Linux)
INFO: stdout 2022-03-28T21:22:01.792619:Chris Rorden's dcm2niiX version v1.0.20190410  GCC6.3.0 (64-bit Linux)
220328-21:22:01,793 nipype.interface INFO:
         stdout 2022-03-28T21:22:01.792619:Found 30 DICOM file(s)
INFO: stdout 2022-03-28T21:22:01.792619:Found 30 DICOM file(s)
220328-21:22:01,793 nipype.interface INFO:
         stdout 2022-03-28T21:22:01.792619:slices not stacked: orientation varies (vNav or localizer?) [1 -0 0 -0 -0 -1] != [-0 1 0 -0 -0 -1]
INFO: stdout 2022-03-28T21:22:01.792619:slices not stacked: orientation varies (vNav or localizer?) [1 -0 0 -0 -0 -1] != [-0 1 0 -0 -0 -1]
220328-21:22:01,793 nipype.interface INFO:
         stdout 2022-03-28T21:22:01.792619:Convert 10 DICOM as /output/run001_heudiconv257_i00021 (256x256x10x1)
INFO: stdout 2022-03-28T21:22:01.792619:Convert 10 DICOM as /output/run001_heudiconv257_i00021 (256x256x10x1)
220328-21:22:01,891 nipype.interface INFO:
         stdout 2022-03-28T21:22:01.891007:Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/output/run001_heudiconv257_i00021.nii"
INFO: stdout 2022-03-28T21:22:01.891007:Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/output/run001_heudiconv257_i00021.nii"
INFO: stdout 2022-03-28T21:22:01.891007:Convert 10 DICOM as /output/run001_heudiconv257_i00011 (256x256x10x1)
220328-21:22:01,891 nipype.interface INFO:
         stdout 2022-03-28T21:22:01.891007:Convert 10 DICOM as /output/run001_heudiconv257_i00011 (256x256x10x1)
220328-21:22:01,984 nipype.interface INFO:
         stdout 2022-03-28T21:22:01.984006:Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/output/run001_heudiconv257_i00011.nii"
INFO: stdout 2022-03-28T21:22:01.984006:Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/output/run001_heudiconv257_i00011.nii"
INFO: stdout 2022-03-28T21:22:01.984006:Convert 10 DICOM as /output/run001_heudiconv257_i00001 (256x256x10x1)
220328-21:22:01,984 nipype.interface INFO:
         stdout 2022-03-28T21:22:01.984006:Convert 10 DICOM as /output/run001_heudiconv257_i00001 (256x256x10x1)
220328-21:22:02,77 nipype.interface INFO:
         stdout 2022-03-28T21:22:02.077853:Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/output/run001_heudiconv257_i00001.nii"
INFO: stdout 2022-03-28T21:22:02.077853:Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/output/run001_heudiconv257_i00001.nii"
220328-21:22:02,78 nipype.interface INFO:
         stdout 2022-03-28T21:22:02.077853:Conversion required 0.305899 seconds (0.028072 for core code).
INFO: stdout 2022-03-28T21:22:02.077853:Conversion required 0.305899 seconds (0.028072 for core code).
220328-21:22:02,111 nipype.workflow INFO:
         [Node] Finished "convert".
INFO: [Node] Finished "convert".
WARNING: Failed to detect fullfilled BIDS layout.  No scans.tsv file(s) will be produced for /output/run0011.json, /output/run0012.json, /output/run0013.json
WARNING: Failed to find task field in /output/run0011.json.
WARNING: Failed to find task field in /output/run0012.json.
WARNING: Failed to find task field in /output/run0013.json.
WARNING: For now not embedding BIDS and info generated .nii.gz itself since sequence produced multiple files
INFO: Converting /output/run002 (176 DICOMs) -> /output . Converter: dcm2niix . Output types: ('nii.gz',)
220328-21:22:02,133 nipype.workflow INFO:
         [Node] Setting-up "convert" in "/tmp/dcm2niixcrj69ysh/convert".
INFO: [Node] Setting-up "convert" in "/tmp/dcm2niixcrj69ysh/convert".
220328-21:22:02,181 nipype.workflow INFO:
         [Node] Running "convert" ("nipype.interfaces.dcm2nii.Dcm2niix"), a CommandLine Interface with command:
dcm2niix -b y -z y -x n -t n -m n -f run002_heudiconv409 -o /output -s n -v n /tmp/dcm2niixcrj69ysh/convert
INFO: [Node] Running "convert" ("nipype.interfaces.dcm2nii.Dcm2niix"), a CommandLine Interface with command:
dcm2niix -b y -z y -x n -t n -m n -f run002_heudiconv409 -o /output -s n -v n /tmp/dcm2niixcrj69ysh/convert
220328-21:22:02,298 nipype.interface INFO:
         stdout 2022-03-28T21:22:02.298862:Chris Rorden's dcm2niiX version v1.0.20190410  GCC6.3.0 (64-bit Linux)
INFO: stdout 2022-03-28T21:22:02.298862:Chris Rorden's dcm2niiX version v1.0.20190410  GCC6.3.0 (64-bit Linux)
220328-21:22:02,299 nipype.interface INFO:
         stdout 2022-03-28T21:22:02.298862:Found 176 DICOM file(s)
INFO: stdout 2022-03-28T21:22:02.298862:Found 176 DICOM file(s)
220328-21:22:02,299 nipype.interface INFO:
         stdout 2022-03-28T21:22:02.298862:Convert 176 DICOM as /output/run002_heudiconv409 (256x256x176x1)
INFO: stdout 2022-03-28T21:22:02.298862:Convert 176 DICOM as /output/run002_heudiconv409 (256x256x176x1)
220328-21:22:02,891 nipype.interface INFO:
         stdout 2022-03-28T21:22:02.891219:Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/output/run002_heudiconv409.nii"
INFO: stdout 2022-03-28T21:22:02.891219:Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/output/run002_heudiconv409.nii"
220328-21:22:02,891 nipype.interface INFO:
         stdout 2022-03-28T21:22:02.891219:Conversion required 0.690064 seconds (0.586886 for core code).
INFO: stdout 2022-03-28T21:22:02.891219:Conversion required 0.690064 seconds (0.586886 for core code).
220328-21:22:02,927 nipype.workflow INFO:
         [Node] Finished "convert".
INFO: [Node] Finished "convert".
WARNING: Failed to detect fullfilled BIDS layout.  No scans.tsv file(s) will be produced for /output/run002.json
WARNING: Failed to find task field in /output/run002.json.
220328-21:22:02,952 nipype.workflow INFO:
         [Node] Setting-up "embedder" in "/tmp/embedmetahl3wg4bz/embedder".
INFO: [Node] Setting-up "embedder" in "/tmp/embedmetahl3wg4bz/embedder".
220328-21:22:02,968 nipype.workflow INFO:
         [Node] Running "embedder" ("nipype.interfaces.utility.wrappers.Function")
INFO: [Node] Running "embedder" ("nipype.interfaces.utility.wrappers.Function")
220328-21:22:09,176 nipype.workflow INFO:
         [Node] Finished "embedder".
INFO: [Node] Finished "embedder".
INFO: Post-treating /output/run002.json file
INFO: Converting /output/run003 (13248 DICOMs) -> /output . Converter: dcm2niix . Output types: ('nii.gz',)
Traceback (most recent call last):
  File "/opt/miniconda-latest/bin/heudiconv", line 33, in <module>
    sys.exit(load_entry_point('heudiconv', 'console_scripts', 'heudiconv')())
  File "/src/heudiconv/heudiconv/cli/run.py", line 24, in main
    workflow(**kwargs)
  File "/src/heudiconv/heudiconv/main.py", line 351, in workflow
    grouping=grouping,)
  File "/src/heudiconv/heudiconv/convert.py", line 216, in prep_conversion
    dcmconfig=dcmconfig,)
  File "/src/heudiconv/heudiconv/convert.py", line 476, in convert
    bids_options, tmpdir, dcmconfig)
  File "/src/heudiconv/heudiconv/convert.py", line 618, in nipype_convert
    convertnode.inputs.source_names = item_dicoms
  File "/opt/miniconda-latest/lib/python3.6/site-packages/nipype/interfaces/base/traits_extension.py", line 426, in validate
    value = super(MultiObject, self).validate(objekt, name, newvalue)
  File "/opt/miniconda-latest/lib/python3.6/site-packages/traits/trait_types.py", line 2473, in validate
    return TraitListObject(self, object, name, value)
  File "/opt/miniconda-latest/lib/python3.6/site-packages/traits/trait_list_object.py", line 582, in __init__
    notifiers=[self.notifier],
  File "/opt/miniconda-latest/lib/python3.6/site-packages/traits/trait_list_object.py", line 210, in __init__
    super().__init__(self.item_validator(item) for item in iterable)
  File "/opt/miniconda-latest/lib/python3.6/site-packages/traits/trait_list_object.py", line 210, in <genexpr>
    super().__init__(self.item_validator(item) for item in iterable)
  File "/opt/miniconda-latest/lib/python3.6/site-packages/traits/trait_list_object.py", line 862, in _item_validator
    return trait_validator(object, self.name, value)
  File "/opt/miniconda-latest/lib/python3.6/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/opt/miniconda-latest/lib/python3.6/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
    self.error(objekt, name, str(value))
  File "/opt/miniconda-latest/lib/python3.6/site-packages/traits/base_trait_handler.py", line 75, in error
    object, name, self.full_info(object, name, value), value
traits.trait_errors.TraitError: Each element of the 'source_names' trait of a Dcm2niixInputSpec instance must be a pathlike object or string representing an existing file, but a value of '/data/crcox/Ser4/i6191681.MRDC.2' <class 'str'> was specified.

```

**Comment by yarikoptic** [comment]
did you do similar conversion before for that so have `${PWD}/Nifti/.heudiconv/crcox` reused may be and which mentions that `i6191681.MRDC.2`?

**Comment by crcox** [comment]
Aha, thank you. That seems to have done it. I'm getting new errors now, but they are errors that I understand how to work with. Thank you!

**Comment by yarikoptic** [comment]
I will close this old report since seems original issue was "resolved".
