### ISSUE TITLE
Heudiconv looking for file that does not exist

### ISSUE THREAD

**Issue by butellyn** [nipy/heudiconv#551]
### Summary

When I run 

```
singularity run --writable-tmpfs --cleanenv \
  -B /projects/b1108/studies/mwmh:/base \
  /home/erb9722/heudiconv_0.9.0.sif \
  -d /base/data/raw/neuroimaging/dicoms/sub-{subject}/*/*/*/*/*.dcm \
  -o /base/data/raw/neuroimaging/bids/ \
  -f /base/scripts/curation/heuristic.py -s MWMH219 -c dcm2niix -b --overwrite
```

I get

```
[](https://github.com/yarikoptic)Traceback (most recent call last):
  File "/opt/miniconda-latest/bin/heudiconv", line 33, in <module>
    sys.exit(load_entry_point('heudiconv', 'console_scripts', 'heudiconv')())
  File "/src/heudiconv/heudiconv/cli/run.py", line 24, in main
    workflow(**kwargs)
  File "/src/heudiconv/heudiconv/main.py", line 351, in workflow
    grouping=grouping,)
  File "/src/heudiconv/heudiconv/convert.py", line 216, in prep_conversion
    dcmconfig=dcmconfig,)
  File "/src/heudiconv/heudiconv/convert.py", line 476, in convert
    bids_options, tmpdir, dcmconfig)
  File "/src/heudiconv/heudiconv/convert.py", line 618, in nipype_convert
    convertnode.inputs.source_names = item_dicoms
  File "/opt/miniconda-latest/lib/python3.6/site-packages/nipype/interfaces/base/traits_extension.py", line 426, in validate
    value = super(MultiObject, self).validate(objekt, name, newvalue)
  File "/opt/miniconda-latest/lib/python3.6/site-packages/traits/trait_types.py", line 2473, in validate
    return TraitListObject(self, object, name, value)
  File "/opt/miniconda-latest/lib/python3.6/site-packages/traits/trait_list_object.py", line 582, in __init__
    notifiers=[self.notifier],
  File "/opt/miniconda-latest/lib/python3.6/site-packages/traits/trait_list_object.py", line 210, in __init__
    super().__init__(self.item_validator(item) for item in iterable)
  File "/opt/miniconda-latest/lib/python3.6/site-packages/traits/trait_list_object.py", line 210, in <genexpr>
    super().__init__(self.item_validator(item) for item in iterable)
  File "/opt/miniconda-latest/lib/python3.6/site-packages/traits/trait_list_object.py", line 862, in _item_validator
    return trait_validator(object, self.name, value)
  File "/opt/miniconda-latest/lib/python3.6/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/opt/miniconda-latest/lib/python3.6/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
    self.error(objekt, name, str(value))
  File "/opt/miniconda-latest/lib/python3.6/site-packages/traits/base_trait_handler.py", line 75, in error
    object, name, self.full_info(object, name, value), value
traits.trait_errors.TraitError: Each element of the 'source_names' trait of a Dcm2niixInputSpec instance must be a pathlike object or string representing an existing file, but a value of '/base/dicoms/sub-MWMH219/ses-1/SCANS/1/DICOM/MWMH219.MR.fMRI_STUDIES_MILLER.1.1.20160601.091443.v9f0wy.dcm' <class 'str'> was specified.
```

I tried going into the container, and `/base/dicoms/sub-MWMH219/ses-1/SCANS/1/DICOM/MWMH219.MR.fMRI_STUDIES_MILLER.1.1.20160601.091443.v9f0wy.dcm` does not exist there, but `/base/data/raw/neuroimaging/dicoms/sub-MWMH219/ses-1/SCANS/1/DICOM/MWMH219.MR.fMRI_STUDIES_MILLER.1.1.20160601.091443.v9f0wy.dcm` does. This latter file follows the structure of the path that I specified in the call to heudiconv. So I guess the question is, why does heudiconv think the former file should exist?

(Continuation of https://github.com/nipy/heudiconv/issues/184)

### Platform details:

Choose one:
- [ ] Local environment

- [x] Container
 0.9.0 from Dockerhub, pulled with Singularity

- Heudiconv version: 0.9.0

**Comment by butellyn** [comment]
Okay, I figured it out. Looks like heudiconv requires (though this is not stated anywhere I can find) that the paths given with the flags be shorter. The following call worked:

```
singularity run --writable-tmpfs --cleanenv --containall \
  -B /projects/b1108/studies/mwmh/data/raw/neuroimaging:/base \
  -B /projects/b1108/studies/mwmh/scripts/curation/heuristic.py:/base/heuristic.py \
  /home/erb9722/heudiconv_0.9.0.sif \
  -d /base/dicoms/sub-{subject}/*/*/*/*/*.dcm \
  -o /base/bids/ \
  -f /base/heuristic.py -s MWMH219 -c dcm2niix -b --overwrite
```
