### ISSUE TITLE
NiPype convert node hanging

### ISSUE THREAD

**Issue by neurorepro** [nipy/heudiconv#584]
### Summary

Running heudiconv (with reproin) hangs when converting data with the latest version installed with pip. The same problem happens when running container latest.

* Example of hanging output with local environment (13-min hang after first convert, then fine):
```
220808-16:06:57,399 nipype.workflow INFO:
	 [Node] Finished "convert", elapsed time 20.521981s.
INFO: [Node] Finished "convert", elapsed time 20.521981s.


220808-16:19:55,606 nipype.workflow INFO:
	 [Node] Setting-up "embedder" in "/tmp/embedmetab670o2tw/embedder".
INFO: [Node] Setting-up "embedder" in "/tmp/embedmetab670o2tw/embedder".
```
* Example of hanging output with container (> 10-min hang after first convert [still waiting]):
```
220808-16:37:56,641 nipype.workflow INFO:
	 [Node] Finished "convert", elapsed time 21.069933s.
INFO: [Node] Finished "convert", elapsed time 21.069933s.

(still waiting at the time of writing this issue)
```
### Platform details:

Choose one:
- [x] Local environment (but same thing with container)

Ubuntu 20.04 LTS
Python 3.9
Installed heudiconv from latest commit with pip (in conda environment)
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.6.15            ha878542_0    conda-forge
certifi                   2022.6.15                pypi_0    pypi
charset-normalizer        2.1.0                    pypi_0    pypi
ci-info                   0.3.0                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
dcmstack                  0.8.0                    pypi_0    pypi
etelemetry                0.3.0                    pypi_0    pypi
filelock                  3.7.1                    pypi_0    pypi
heudiconv                 0.11.3.post7+g64569f1           dev_0    <develop>
idna                      3.3                      pypi_0    pypi
isodate                   0.6.1                    pypi_0    pypi
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.12               h166bdaf_2    conda-forge
looseversion              1.0.1                    pypi_0    pypi
lxml                      4.9.1                    pypi_0    pypi
ncurses                   6.3                  h27087fc_1    conda-forge
networkx                  2.8.5                    pypi_0    pypi
nibabel                   4.0.1                    pypi_0    pypi
nipype                    1.8.3                    pypi_0    pypi
numpy                     1.23.1                   pypi_0    pypi
openssl                   3.0.5                h166bdaf_1    conda-forge
packaging                 21.3                     pypi_0    pypi
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
prov                      2.0.0                    pypi_0    pypi
pydicom                   2.3.0                    pypi_0    pypi
pydot                     1.4.2                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
python                    3.9.13          h2660328_0_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.9                      2_cp39    conda-forge
rdflib                    6.2.0                    pypi_0    pypi
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.28.1                   pypi_0    pypi
scipy                     1.9.0                    pypi_0    pypi
setuptools                63.3.0           py39hf3d152e_0    conda-forge
simplejson                3.17.6                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sqlite                    3.39.2               h4ff8645_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
traits                    6.3.2                    pypi_0    pypi
tzdata                    2022a                h191b570_0    conda-forge
urllib3                   1.26.11                  pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.12               h166bdaf_2    conda-forge

```

- [x] Container

Same result with container [v0.11.3](https://hub.docker.com/layers/heudiconv/nipy/heudiconv/v0.11.3/images/sha256-2ec24547e9a7a9f90d5bac31c0ed49d1625467f4ea92eadbd934cfb683190e8a?context=explore)

- Heudiconv version:

**Comment by yarikoptic** [comment]
@satra any ideas on what this hanging could be about?

@neurorepro you might like to rerun while setting `HEUDICONV_LOG_LEVEL=DEBUG` -- although unlikely but may be somehow it is stalling at heudiconv level?  also if you install https://pypi.org/project/py-spy/0.1.0/ and use it to monitor that stalled process may be you would be able to see where it is stalled? or may be whenever you Ctrl-C it - it would already show the traceback for that location?

**Comment by neurorepro** [comment]
@yarikoptic thank you for the feedback, i was posting mostly in case this was something known (with a known solution), but indeed it'd be great to find out what is causing the hang if possible.

I am going to send you the output of the different approaches you mentioned. First here is the trace from Ctrl-C when hanging:
```console
^CTraceback (most recent call last):
  File "/opt/miniconda-latest/bin/heudiconv", line 33, in <module>
    sys.exit(load_entry_point('heudiconv', 'console_scripts', 'heudiconv')())
  File "/src/heudiconv/heudiconv/cli/run.py", line 24, in main
    workflow(**kwargs)
  File "/src/heudiconv/heudiconv/main.py", line 393, in workflow
    grouping=grouping,)
  File "/src/heudiconv/heudiconv/convert.py", line 217, in prep_conversion
    dcmconfig=dcmconfig,)
  File "/src/heudiconv/heudiconv/convert.py", line 519, in convert
    outdir, tempdirs, symlink, overwrite)
  File "/src/heudiconv/heudiconv/convert.py", line 644, in convert_dicom
    overwrite)
  File "/src/heudiconv/heudiconv/dicoms.py", line 393, in compress_dicoms
    filter=_assign_dicom_time)
  File "/opt/miniconda-latest/lib/python3.7/tarfile.py", line 1944, in add
    self.addfile(tarinfo, f)
  File "/opt/miniconda-latest/lib/python3.7/tarfile.py", line 1972, in addfile
    copyfileobj(fileobj, self.fileobj, tarinfo.size, bufsize=bufsize)
  File "/opt/miniconda-latest/lib/python3.7/tarfile.py", line 250, in copyfileobj
    dst.write(buf)
  File "/opt/miniconda-latest/lib/python3.7/gzip.py", line 275, in write
    self.fileobj.write(self.compress.compress(data))
KeyboardInterrupt
DEBUG: Removing 1 temporary directories
DEBUG: Removing /tmp/heudiconvDCMpxkyw_la
DEBUG: Removing 0 temporary directories
DEBUG: Removing 0 temporary directories

```

**Comment by neurorepro** [comment]
<details>
  <summary>
    And here the output of the verbose debug
  </summary>
  
  ```console
DEBUG: Starting the abomination
DEBUG: Starting new HTTPS connection (1): rig.mit.edu:443
WARNING: Could not check for version updates: Connection to server could not be made
INFO: Running heudiconv version 0.11.3+d20220512 latest Unknown
INFO: Analyzing 2400 dicoms
INFO: Filtering out 0 dicoms based on their filename
DEBUG: 1.3.12.2.1107.5.2.43.66054.30000022070106500294200000010    5-func_acq-nav_task-spatial   func_acq-nav_task-spatial   func_acq-nav_task-spatial False nref=3  nsrc=66 ('ORIGINAL', 'PRIMARY', 'M', 'ND', 'MOSAIC')
INFO: Generated sequence info for 1 studies with 1 entries total
INFO: Processing sequence infos to deduce study/session
INFO: Study session for StudySessionInfo(locator='X/Y', session=None, subject='ABCD')
INFO: Need to process 1 study sessions
INFO: PROCESSING STARTS: {'subject': 'ABCD', 'outdir': '/base/bids_testhang3/X/Y', 'session': None}
INFO: Processing 1 pre-sorted seqinfo entries
DEBUG: Calling out to <module 'heudiconv.heuristics.reproin' from '/src/heudiconv/heudiconv/heuristics/reproin.py'>.infodict
INFO: Processing 1 seqinfo entries
DEBUG: Writing to /base/bids_testhang3/X/Y/.heudiconv/ABCD/info/ABCD.auto.txt, /base/bids_testhang3/X/Y/.heudiconv/ABCD/info/ABCD.edit.txt, /base/bids_testhang3/X/Y/.heudiconv/ABCD/info/filegroup.json
INFO: Doing conversion using dcm2niix
INFO: Converting /base/bids_testhang3/X/Y/sub-ABCD/func/sub-ABCD_task-spatial_acq-nav_bold (2400 DICOMs) -> /base/bids_testhang3/X/Y/sub-ABCD/func . Converter: dcm2niix . Output types: ('nii.gz', 'dicom')
DEBUG: Processing 2400 dicoms for output type nii.gz. Overwrite=False
DEBUG: Includes the following dicoms: ['/base/dicom_testhang/05_pilot1_func_acq-nav_task-spatial_20220701153833/00001.dcm', '/base/dicom_testhang/05_pilot1_func_acq-nav_task-spatial_20220701153833/00002.dcm', ..., '/base/dicom_testhang/05_pilot1_func_acq-nav_task-spatial_20220701153833/02400.dcm']
DEBUG: Starting new HTTPS connection (1): rig.mit.edu:443
220809-06:42:23,346 nipype.workflow INFO:
	 [Node] Setting-up "convert" in "/tmp/dcm2niix_cp36c3q/convert".
INFO: [Node] Setting-up "convert" in "/tmp/dcm2niix_cp36c3q/convert".
220809-06:42:24,161 nipype.workflow INFO:
	 [Node] Executing "convert" <nipype.interfaces.dcm2nii.Dcm2niix>
INFO: [Node] Executing "convert" <nipype.interfaces.dcm2nii.Dcm2niix>
DEBUG: Starting new HTTPS connection (1): rig.mit.edu:443
220809-06:42:34,955 nipype.interface INFO:
	 stdout 2022-08-09T06:42:34.955209:Chris Rorden's dcm2niiX version v1.0.20211006  GCC10.2.1 x86-64 (64-bit Linux)
INFO: stdout 2022-08-09T06:42:34.955209:Chris Rorden's dcm2niiX version v1.0.20211006  GCC10.2.1 x86-64 (64-bit Linux)
220809-06:42:34,956 nipype.interface INFO:
	 stdout 2022-08-09T06:42:34.955209:Found 2400 DICOM file(s)
INFO: stdout 2022-08-09T06:42:34.955209:Found 2400 DICOM file(s)
220809-06:42:34,956 nipype.interface INFO:
	 stdout 2022-08-09T06:42:34.955209:Convert 2400 DICOM as /base/bids_testhang3/X/Y/sub-ABCD/func/sub-ABCD_task-spatial_acq-nav_bold_heudiconv593 (104x104x66x2400)
INFO: stdout 2022-08-09T06:42:34.955209:Convert 2400 DICOM as /base/bids_testhang3/X/Y/sub-ABCD/func/sub-ABCD_task-spatial_acq-nav_bold_heudiconv593 (104x104x66x2400)
220809-06:42:50,402 nipype.interface INFO:
	 stdout 2022-08-09T06:42:50.401919:Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/base/bids_testhang3/X/Y/sub-ABCD/func/sub-ABCD_task-spatial_acq-nav_bold_heudiconv593.nii"
INFO: stdout 2022-08-09T06:42:50.401919:Compress: "/usr/bin/pigz" -b 960 -n -f -6 "/base/bids_testhang3/X/Y/sub-ABCD/func/sub-ABCD_task-spatial_acq-nav_bold_heudiconv593.nii"
220809-06:42:50,402 nipype.interface INFO:
	 stdout 2022-08-09T06:42:50.401919:Conversion required 21.091742 seconds (9.343968 for core code).
INFO: stdout 2022-08-09T06:42:50.401919:Conversion required 21.091742 seconds (9.343968 for core code).
220809-06:42:50,460 nipype.workflow INFO:
	 [Node] Finished "convert", elapsed time 21.195289s.
INFO: [Node] Finished "convert", elapsed time 21.195289s.
DEBUG: Processing 2400 dicoms for output type dicom. Overwrite=False
DEBUG: Includes the following dicoms: ['/base/dicom_testhang/05_pilot1_func_acq-nav_task-spatial_20220701153833/00001.dcm', '/base/dicom_testhang/05_pilot1_func_acq-nav_task-spatial_20220701153833/00002.dcm', ...,  '/base/dicom_testhang/05_pilot1_func_acq-nav_task-spatial_20220701153833/02400.dcm']
DEBUG: Starting new HTTPS connection (1): rig.mit.edu:443
DEBUG: Embedding into /base/bids_testhang3/X/Y/sub-ABCD/func/sub-ABCD_task-spatial_acq-nav_bold.json based on dicoms[0]=/base/dicom_testhang/05_pilot1_func_acq-nav_task-spatial_20220701153833/00001.dcm for nifti /base/bids_testhang3/X/Y/sub-ABCD/func/sub-ABCD_task-spatial_acq-nav_bold.nii.gz
220809-06:55:32,70 nipype.workflow INFO:
	 [Node] Setting-up "embedder" in "/tmp/embedmetaoecwynig/embedder".
INFO: [Node] Setting-up "embedder" in "/tmp/embedmetaoecwynig/embedder".
220809-06:55:32,278 nipype.workflow INFO:
	 [Node] Executing "embedder" <nipype.interfaces.utility.wrappers.Function>
INFO: [Node] Executing "embedder" <nipype.interfaces.utility.wrappers.Function>
DEBUG: no data received!
DEBUG: no probers hit minimum threshold
DEBUG: no data received!
DEBUG: no probers hit minimum threshold
DEBUG: no data received!
DEBUG: no probers hit minimum threshold
DEBUG: no data received!
DEBUG: no probers hit minimum threshold
DEBUG: no data received!

######################################################
# Another 9595 times the same message as above, then:
######################################################

DEBUG: no probers hit minimum threshold
220809-06:59:50,585 nipype.workflow INFO:
	 [Node] Finished "embedder", elapsed time 258.30585s.
INFO: [Node] Finished "embedder", elapsed time 258.30585s.
INFO: Post-treating /base/bids_testhang3/X/Y/sub-ABCD/func/sub-ABCD_task-spatial_acq-nav_bold.json file
INFO: Adding "IntendedFor" to the fieldmaps in /base/bids_testhang3/X/Y/sub-ABCD.
WARNING: We cannot add the IntendedFor field: no fmap/ in /base/bids_testhang3/X/Y/sub-ABCD
DEBUG: Removing 1 temporary directories
DEBUG: Removing /tmp/embedmetaoecwynig
DEBUG: Attempting to acquire lock 140264405050064 on /base/bids_testhang3/X/Y/heudiconv.lock
DEBUG: Lock 140264405050064 acquired on /base/bids_testhang3/X/Y/heudiconv.lock
INFO: Populating template files under /base/bids_testhang3/X/Y
DEBUG: Generating /base/bids_testhang3/X/Y/sub-ABCD/func/sub-ABCD_task-spatial_acq-nav_events.tsv
DEBUG: Generating /base/bids_testhang3/X/Y/task-spatial_acq-nav_bold.json
DEBUG: Attempting to release lock 140264405050064 on /base/bids_testhang3/X/Y/heudiconv.lock
DEBUG: Lock 140264405050064 released on /base/bids_testhang3/X/Y/heudiconv.lock
INFO: PROCESSING DONE: {'subject': 'ABCD', 'outdir': '/base/bids_testhang3/X/Y', 'session': None}
DEBUG: Removing 1 temporary directories
DEBUG: Removing /tmp/heudiconvDCMm0wco_td
DEBUG: Removing 0 temporary directories
  ```
</details>

**Comment by neurorepro** [comment]
<details>
  <summary>
    And here the output of py-spy to where it is stalled (gzip write)
  </summary>

```console
Process 1098440: python /mnt/projects/bids/code/test_heudiconv_hang.py
Python v3.9.13 (/home/michael/.conda/envs/reproin39dev/bin/python3.9)

Thread 1098440 (active): "MainThread"
    write (gzip.py:288)
        Arguments:
            self: <GzipFile at 0x7f92f89e2d90>
            data: <bytes at 0x55fc1aa7b5a0>
        Locals:
            length: 16384
    copyfileobj (tarfile.py:250)
        Arguments:
            src: <_io.BufferedReader at 0x7f92f8d42e00>
            dst: <GzipFile at 0x7f92f89e2d90>
            length: 1943670
            exception: <type at 0x55fc1903c8a0>
            bufsize: 16384
        Locals:
            blocks: 118
            remainder: 10358
            b: 12
            buf: <bytes at 0x55fc1aa7b5a0>
    addfile (tarfile.py:2016)
        Arguments:
            self: <TarFile at 0x7f92f89e23a0>
            tarinfo: <TarInfo at 0x7f92f8d87580>
            fileobj: <_io.BufferedReader at 0x7f92f8d42e00>
        Locals:
            buf: <bytes at 0x55fc1a918190>
            bufsize: None
    add (tarfile.py:1988)
        Arguments:
            self: <TarFile at 0x7f92f89e23a0>
            name: "/tmp/dicomtarc913b1ah/00406.dcm"
            arcname: "sub-012345_task-spatial_acq-nav_bold/00406.dcm"
            recursive: False
        Locals:
            filter: <function at 0x7f92f8d64670>
            tarinfo: <TarInfo at 0x7f92f8abef40>
            f: <_io.BufferedReader at 0x7f92f8d42e00>
    compress_dicoms (heudiconv/dicoms.py:389)
        Arguments:
            dicom_list: ["/mnt/projects/007/dicom_testhang/05_pilot1_func_acq-nav_task-spatial_20420401153833/00001.dcm", "/mnt/projects/007/dicom_testhang/05_pilot1_func_acq-nav_task-spatial_20420401153833/00002.dcm", "/mnt/projects/007/dicom_testhang/05_pilot1_func_acq-nav_task-spatial_20420401153833/00003.dcm", "/mnt/projects/007/dicom_testhang/05_pilot1_func_acq-nav_task-spatial_20420401153833/00004.dcm", ...]
            out_prefix: "/mnt/projects/007/bids_testhanglocal1/X/Y/sourcedata/sub-012345/func/sub-012345_task-spatial_acq-nav_bold"
            tempdirs: <TempDirs at 0x7f92f8ebe5b0>
            overwrite: False
        Locals:
            tmpdir: "/tmp/dicomtarc913b1ah"
            outtar: "/mnt/projects/007/bids_testhanglocal1/X/Y/sourcedata/sub-012345/func/sub-012345_task-spatial_acq-nav_bold.dicom.tgz"
            _assign_dicom_time: <function at 0x7f92f8d64670>
            time: <module at 0x7f92fcbe27c0>
            _old_time: <builtin_function_or_method at 0x7f92fcbe2860>
            tar: <TarFile at 0x7f92f89e23a0>
            filename: "/mnt/projects/007/dicom_testhang/05_pilot1_func_acq-nav_task-spatial_20420401153833/00406.dcm"
            outfile: "/tmp/dicomtarc913b1ah/00406.dcm"
    convert_dicom (heudiconv/convert.py:641)
        Arguments:
            item_dicoms: ["/mnt/projects/007/dicom_testhang/05_pilot1_func_acq-nav_task-spatial_20420401153833/00001.dcm", "/mnt/projects/007/dicom_testhang/05_pilot1_func_acq-nav_task-spatial_20420401153833/00002.dcm", "/mnt/projects/007/dicom_testhang/05_pilot1_func_acq-nav_task-spatial_20420401153833/00003.dcm", "/mnt/projects/007/dicom_testhang/05_pilot1_func_acq-nav_task-spatial_20420401153833/00004.dcm", ...]
            bids_options: []
            prefix: "/mnt/projects/007/bids_testhanglocal1/X/Y/sub-012345/func/sub-012345_task-spatial_acq-nav_bold"
            outdir: "/mnt/projects/007/bids_testhanglocal1/X/Y"
            tempdirs: <TempDirs at 0x7f92f8ebe5b0>
            symlink: True
            overwrite: False
        Locals:
            sourcedir: "/mnt/projects/007/bids_testhanglocal1/X/Y/sourcedata"
            sourcedir_: "/mnt/projects/007/bids_testhanglocal1/X/Y/sourcedata/sub-012345/func"
    convert (heudiconv/convert.py:518)
        Arguments:
            items: [("/mnt/projects/007/bids_testhanglocal1/X/Y/sub-012345/func/sub-012345_task-spatial_acq-nav_bold", ("nii.gz", "dicom"), ["/mnt/projects/007/dicom_testhang/05_pilot1_func_acq-nav_task-spatial_20420401153833/00001.dcm", "/mnt/projects/007/dicom_testhang/05_pilot1_func_acq-nav_task-spatial_20420401153833/00002.dcm", ...])]
            converter: "dcm2niix"
            scaninfo_suffix: ".json"
            custom_callable: None
            with_prov: False
            bids_options: []
            outdir: "/mnt/projects/007/bids_testhanglocal1/X/Y"
            min_meta: False
            overwrite: False
            symlink: True
            prov_file: None
            dcmconfig: None
            populate_intended_for_opts: {"matching_parameters": ["ImagingVolume", "Shims"], "criterion": "Closest"}
        Locals:
            prov_files: []
            tempdirs: <TempDirs at 0x7f92f8ebe5b0>
            item_idx: 0
            item: ("/mnt/projects/007/bids_testhanglocal1/X/Y/sub-012345/func/sub-012345_task-spatial_acq-nav_bold", ("nii.gz", "dicom"), ["/mnt/projects/007/dicom_testhang/05_pilot1_func_acq-nav_task-spatial_20420401153833/00001.dcm", "/mnt/projects/007/dicom_testhang/05_pilot1_func_acq-nav_task-spatial_20420401153833/00002.dcm", ...])
            prefix: "/mnt/projects/007/bids_testhanglocal1/X/Y/sub-012345/func/sub-012345_task-spatial_acq-nav_bold"
            outtypes: ("nii.gz", "dicom")
            item_dicoms: ["/mnt/projects/007/dicom_testhang/05_pilot1_func_acq-nav_task-spatial_20420401153833/00001.dcm", "/mnt/projects/007/dicom_testhang/05_pilot1_func_acq-nav_task-spatial_20420401153833/00002.dcm", "/mnt/projects/007/dicom_testhang/05_pilot1_func_acq-nav_task-spatial_20420401153833/00003.dcm", "/mnt/projects/007/dicom_testhang/05_pilot1_func_acq-nav_task-spatial_20420401153833/00004.dcm", ...]
            prefix_dirname: "/mnt/projects/007/bids_testhanglocal1/X/Y/sub-012345/func"
            outname_bids: "/mnt/projects/007/bids_testhanglocal1/X/Y/sub-012345/func/sub-012345_task-spatial_acq-nav_bold.json"
            bids_outfiles: ["/mnt/projects/007/bids_testhanglocal1/X/Y/sub-012345/func/sub-012345_task-spatial_acq-nav_bold.json"]
            outname: "/mnt/projects/007/bids_testhanglocal1/X/Y/sub-012345/func/sub-012345_task-spatial_acq-nav_bold.nii.gz"
            scaninfo: "/mnt/projects/007/bids_testhanglocal1/X/Y/sub-012345/func/sub-012345_task-spatial_acq-nav_bold.json"
            dicom_only: False
            outtype: "dicom"
            tmpdir: "/tmp/dcm2niixwcbohllz"
            res: <InterfaceResult at 0x7f92f8c21e50>
    prep_conversion (heudiconv/convert.py:207)
        Arguments:
            sid: "012345"
            dicoms: None
            outdir: "/mnt/projects/007/bids_testhanglocal1/X/Y"
            heuristic: <module at 0x7f92f8ea0860>
            converter: "dcm2niix"
            anon_sid: "012345"
            anon_outdir: "/mnt/projects/007/bids_testhanglocal1/X/Y"
            with_prov: False
            ses: None
            bids_options: []
            seqinfo: {...}
            min_meta: False
            overwrite: False
            dcmconfig: None
            grouping: "studyUID"
        Locals:
            idir: "/mnt/projects/007/bids_testhanglocal1/X/Y/.heudiconv/012345/info"
            ses_suffix: ""
            info_file: "/mnt/projects/007/bids_testhanglocal1/X/Y/.heudiconv/012345/info/012345.auto.txt"
            edit_file: "/mnt/projects/007/bids_testhanglocal1/X/Y/.heudiconv/012345/info/012345.edit.txt"
            filegroup_file: "/mnt/projects/007/bids_testhanglocal1/X/Y/.heudiconv/012345/info/filegroup.json"
            reuse_conversion_table: False
            target_heuristic_filename: "/mnt/projects/007/bids_testhanglocal1/X/Y/.heudiconv/012345/info/heuristic.py"
            old_heuristic_filename: "/mnt/projects/007/bids_testhanglocal1/X/Y/.heudiconv/012345/info/reproin.py"
            info: {("{bids_subject_session_dir}/func/{bids_subject_session_prefix}_task-spatial_acq-nav_bold", ("nii.gz", "dicom"), None): ["5-func_acq-nav_task-spatial"]}
            filegroup: {...}
            seqinfo_list: [(2400, "00001.dcm", "5-func_acq-nav_task-spatial", "05_pilot1_func_acq-nav_task-spatial_20420401153833", 2400, "", 104, 104, 66, 2400, 1.02, 34, "func_acq-nav_task-spatial", False, False, "012345", "X^Y", "", "func_acq-nav_task-spatial", "*epfid2d1_012", ("ORIGINAL", "PRIMARY", "M", "ND", "MOSAIC"), "", "042Y", "F", "20420401", "1.3.12.2.1107.5.2.43.66054.2042040115550153636017854.0.0.0", "120321.123400")]
            dicominfo_file: "/mnt/projects/007/bids_testhanglocal1/X/Y/.heudiconv/012345/info/dicominfo.tsv"
            fp: <_io.TextIOWrapper at 0x7f92f8f041e0>
            seq: (2400, "00001.dcm", "5-func_acq-nav_task-spatial", "05_pilot1_func_acq-nav_task-spatial_20420401153833", 2400, "", 104, 104, 66, 2400, 1.02, 34, "func_acq-nav_task-spatial", False, False, "012345", "X^Y", "", "func_acq-nav_task-spatial", "*epfid2d1_012", ("ORIGINAL", "PRIMARY", "M", "ND", "MOSAIC"), "", "042Y", "F", "20420401", "1.3.12.2.1107.5.2.43.66054.2042040115550153636017854.0.0.0", "120321.123400")
            tdir: "/mnt/projects/007/bids_testhanglocal1/X/Y"
            cinfo: [("/mnt/projects/007/bids_testhanglocal1/X/Y/sub-012345/func/sub-012345_task-spatial_acq-nav_bold", ("nii.gz", "dicom"), ["/mnt/projects/007/dicom_testhang/05_pilot1_func_acq-nav_task-spatial_20420401153833/00001.dcm", "/mnt/projects/007/dicom_testhang/05_pilot1_func_acq-nav_task-spatial_20420401153833/00002.dcm", ...])]
    workflow (heudiconv/main.py:379)
        Locals:
            dicom_dir_template: None
            files: ["/mnt/projects/007/dicom_testhang"]
            subjs: None
            converter: "dcm2niix"
            outdir: "/mnt/projects/007/bids_testhanglocal1"
            locator: "X/Y"
            conv_outdir: None
            anon_cmd: None
            heuristic: <module at 0x7f92f8ea0860>
            with_prov: False
            session: None
            bids_options: []
            overwrite: False
            datalad: False
            debug: False
            command: None
            grouping: "studyUID"
            minmeta: False
            random_seed: None
            dcmconfig: None
            queue: None
            queue_args: None
            latest: None
            etelemetry: <module at 0x7f92f924ff90>
            study_sessions: {("X/Y", None, "012345"): {...}}
            locator_manual: None
            session_manual: None
            sid: "012345"
            files_or_seqinfo: {...}
            dicoms: None
            seqinfo: {...}
            anon_sid: None
            study_outdir: "/mnt/projects/007/bids_testhanglocal1/X/Y"
            anon_outdir: "/mnt/projects/007/bids_testhanglocal1"
            anon_study_outdir: "/mnt/projects/007/bids_testhanglocal1/X/Y"
    main (heudiconv/cli/run.py:24)
        Arguments:
            argv: ["-o", "/mnt/projects/007/bids_testhanglocal1", "--files", "/mnt/projects/007/dicom_testhang", "-f", "reproin", "--bids"]
        Locals:
            parser: <ArgumentParser at 0x7f92fcadcf10>
            args: <Namespace at 0x7f92f8ef1070>
            kwargs: {"dicom_dir_template": None, "files": ["/mnt/projects/007/dicom_testhang"], "subjs": None, "converter": "dcm2niix", "outdir": "/mnt/projects/007/bids_testhanglocal1", "locator": None, "conv_outdir": None, "anon_cmd": None, "heuristic": "reproin", "with_prov": False, "session": None, "bids_options": [], "overwrite": False, "datalad": False, "debug": False, "command": None, "grouping": "studyUID", "minmeta": False, "random_seed": None, ...}
    <module> (test_heudiconv_hang.py:10)
```
</details>

**Comment by neurorepro** [comment]
Just to emphasize that after the ~15 mins hang then it continues fine (conversion, gzip, etc. of other sequences do not have the 13-min delay).

The verbose output posted [above](https://github.com/nipy/heudiconv/issues/584#issuecomment-1209009533) is only for one sequence though (i created a minimal 1-sequence example of the hang after facing the issue).

**Comment by yarikoptic** [comment]
"hang"  -- is it really a "hang" (doing nothing) or "very slow" IO (judging from traceback) for some reason?  is there IO or CPU load? may be `strace `ing that process you would see if `read` syscalls are still happening while "hanging" or it would show that it is `wait`ing on something?

**Comment by neurorepro** [comment]
Will post `strace` output. It has hundreds of lines per second. Not sure why it takes such long time for first sequence conversion and then much faster for other sequences. It did the same on another machine (with docker, cf above).

**Comment by neurorepro** [comment]
Ok so strace matching the "hanging" period (16:58:34,906 to 17:13:50,470) is [there](https://www.dropbox.com/s/zc073gus8441wyo/heudistracet_hangperiod.log?dl=0). After some digging with other tests it looks like the "hanging" is roughly proportional to the number of files, so that may be just slow IO indeed (nvme drive doesn't seem to help), e.g.:
* ~13 mins for sequence with 2400 dcm files
* ~1 min 20 sec for sequence with 140 dcm files

In my case i'm trying to put heudiconv in production at institute level so the 13 mins seem quite long but it looks like it was just an exceptionally long sequence, and that's just the time required by `dcm2niix`.

Looks like [`dcm2niiXL`](https://github.com/neurolabusc/dcm2niiXL) or `dcm2niix` with other compression options could help speed up things.

In any thanks a lot @yarikoptic and @satra for helping investigating this and being so responsive.

**Comment by yarikoptic** [comment]
> Ok so strace matching the "hanging" period (16:58:34,906 to 17:13:50,470) is [there](https://www.dropbox.com/s/zc073gus8441wyo/heudistracet_hangperiod.log?dl=0).

FWIW, I (`site-dropbox@onerussian.com`) do not have access to it.  So looking at [earlier shown log](https://github.com/nipy/heudiconv/issues/584#issuecomment-1209283581) it is taking awhile to get from `convert` to `embeder node`, right?  you could add

```patch
diff --git a/heudiconv/convert.py b/heudiconv/convert.py
index d69baa2..d30323f 100644
--- a/heudiconv/convert.py
+++ b/heudiconv/convert.py
@@ -530,7 +530,7 @@ def convert(items, converter, scaninfo_suffix, custom_callable, with_prov,
                     # run conversion through nipype
                     res, prov_file = nipype_convert(item_dicoms, prefix, with_prov,
                                                     bids_options, tmpdir, dcmconfig)
-
+                    import pdb; pdb.set_trace()
                     bids_outfiles = save_converted_files(res, item_dicoms, bids_options,
                                                          outtype, prefix,
                                                          outname_bids,
```
and then step through to see which step takes most of the time at higher than strace level.  And according to your observations above it is the archival of dicoms under `sourcedata/` we do after converting to niftis typically due to order of  outtype=('nii.gz', 'dicom')` and thus calling https://github.com/nipy/heudiconv/blob/master/heudiconv/convert.py#L518 after, etc....  Then your filesystem needs to read/write/compress and somehow that IO seems to be slowish.

extra metadata embedder is also (known) to be slow and you confirm that: `Finished "embedder", elapsed time 258.30585s`.

I also noticed that there is 

```
DEBUG: Starting new HTTPS connection (1): rig.mit.edu:443
``` 
and 
- it happens multiple times! (likely for different components)
- there is currently a problem that the server is down so it would just wait to timeout: https://github.com/sensein/etelemetry-client/issues/35 .
- it shouldn't relate to the number of files though, unless due to that multiple invocations we manage to do it then per each group of files within pool of dicoms.
- if not the main/major contributor -- still might be contributing to the delay

I wish we had more consistent timestamping in our heudiconv logs so we could use smth like https://github.com/datalad/datalad/blob/master/tools/dtime to see quickly how long it took from one log line to the next one ;)

So -- seems to be cocktail of reasons ;)
