### ISSUE TITLE
dev install of local package fails

### ISSUE THREAD

**Issue by Remi-Gau** [nipy/heudiconv#585]
Actually even the non dev install fails.

Using virtualenv

```bash
python --version

Python 3.8.0
```

```bash
pip list

Package    Version
---------- -------
pip        22.2.2
setuptools 63.1.0
wheel      0.37.1
```

See full error at the end.

Not a expert in python packaging but it seems that there is `_version.py` missing in the heudiconv folder as it is referenced in the pyproject.toml and heudiconv/__init__.py.

But it seems to also be ignored in the .gitignore. Am I missing something?

<details>
<summary>error</summary>

```python
pip install -r dev-requirements.txt 

Processing /home/remi/github/heudiconv
Installing build dependencies ... done
Getting requirements to build wheel ... error
error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [63 lines of output]
      Traceback (most recent call last):
        File "/tmp/pip-build-env-fc2vjgtu/overlay/lib/python3.8/site-packages/versioningit/git.py", line 350, in describe_git_core
          tag, distance, rev = Describe.parse(description)
        File "/tmp/pip-build-env-fc2vjgtu/overlay/lib/python3.8/site-packages/versioningit/git.py", line 56, in parse
          raise ValueError("Could not parse `git describe` output")
      ValueError: Could not parse `git describe` output
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/tmp/pip-build-env-fc2vjgtu/overlay/lib/python3.8/site-packages/versioningit/hook.py", line 18, in setuptools_finalizer
          version = get_version(PROJECT_ROOT, write=True, fallback=True)
        File "/tmp/pip-build-env-fc2vjgtu/overlay/lib/python3.8/site-packages/versioningit/core.py", line 308, in get_version
          version = vgit.get_version()
        File "/tmp/pip-build-env-fc2vjgtu/overlay/lib/python3.8/site-packages/versioningit/core.py", line 149, in get_version
          description = self.do_vcs()
        File "/tmp/pip-build-env-fc2vjgtu/overlay/lib/python3.8/site-packages/versioningit/core.py", line 188, in do_vcs
          description = self.vcs(project_dir=self.project_dir)
        File "/tmp/pip-build-env-fc2vjgtu/overlay/lib/python3.8/site-packages/versioningit/methods.py", line 154, in __call__
          return self.method(params=self.params, **kwargs)
        File "/tmp/pip-build-env-fc2vjgtu/overlay/lib/python3.8/site-packages/versioningit/git.py", line 227, in describe_git
          vdesc = describe_git_core(
        File "/tmp/pip-build-env-fc2vjgtu/overlay/lib/python3.8/site-packages/versioningit/git.py", line 362, in describe_git_core
          raise NoTagError("`git describe` could not find a tag")
      versioningit.errors.NoTagError: `git describe` could not find a tag
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/remi/github/heudiconv/env/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/remi/github/heudiconv/env/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/remi/github/heudiconv/env/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-fc2vjgtu/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/tmp/pip-build-env-fc2vjgtu/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-fc2vjgtu/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(code, locals())
        File "<string>", line 80, in <module>
        File "<string>", line 51, in main
        File "/tmp/pip-build-env-fc2vjgtu/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-fc2vjgtu/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/tmp/pip-build-env-fc2vjgtu/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 476, in __init__
          _Distribution.__init__(
        File "/tmp/pip-build-env-fc2vjgtu/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 280, in __init__
          self.finalize_options()
        File "/tmp/pip-build-env-fc2vjgtu/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 900, in finalize_options
          ep(self)
        File "/tmp/pip-build-env-fc2vjgtu/overlay/lib/python3.8/site-packages/versioningit/hook.py", line 23, in setuptools_finalizer
          raise RuntimeError(
      RuntimeError:
      versioningit could not find a version for the project in /home/remi/github/heudiconv!
      
      You may be installing from a shallow clone, in which case you need to unshallow it first.
      
      Alternatively, you may be installing from a Git archive, which is not supported by default.  Install from a git+https://... URL instead.
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```
</details>

**Comment by yarikoptic** [comment]
>  versioningit.errors.NoTagError: `git describe` could not find a tag

was it a shallow clone of git repo?  shouldn't do that! ;)

**Comment by yarikoptic** [comment]
thought to complain to `versioningit` about providing moreinformation, but then spotted that at the end it did say

```
      RuntimeError:
      versioningit could not find a version for the project in /home/remi/github/heudiconv!
      
      You may be installing from a shallow clone, in which case you need to unshallow it first.
      
      Alternatively, you may be installing from a Git archive, which is not supported by default.  Install from a git+https://... URL instead.
      
      ```

so I am not sure if there is anything else we could/should do about this issue besides may be improving documentation... added a rudimentary "How to contribute" section to README.rst and mentioned the necessity for non-shallow clone. Done in 1287cab9ddd22044e1185582163aa3fae61e6654  . Feel free to reopen with more specific instructions on what else to do to resolve.

**Comment by yarikoptic** [comment]
it is a shallow clone, at  https://github.com/Remi-Gau/heudiconv/runs/7754074976?check_suite_focus=true#step:2:4 it says `fetch-depth: 1` and there at https://github.com/Remi-Gau/heudiconv/actions/runs/2827950931/workflow#L21 in the "source".   Make it `fetch-depth: 0`

**Comment by Remi-Gau** [comment]
Sorry I meant my local clone was not shallow.

In CI with `fetch-depth: 0`
https://github.com/Remi-Gau/heudiconv/runs/7782309341?check_suite_focus=true#step:2:4

Still the same error

**Comment by yarikoptic** [comment]
oh, it is from your fork... you haven't pushed a single tag there: https://github.com/Remi-Gau/heudiconv/tags

**Comment by Remi-Gau** [comment]
ah it worked yay!

may be worth adding  to the contributing doc that tags are required for a local install if cloned from a fork? Want me to do it?
