### ISSUE TITLE
INFO: Processing 0 dicoms

### ISSUE THREAD

**Issue by meribach** [nipy/heudiconv#68]
Dear experts,
starting for the first time trying to use the docker version of heudiconv, with Siemens dicom files. I am launching the following from my command prompt (Windows 10). So it seams not to find the dicom files. Any help or suggestion is welcome. Attached a screenshot of where my data is. Thanks in advance for your help. 
C:\Users\admin\data>docker run --rm -it -v C:/Users/admin/data nipy/heudiconv -d C:/Users/admin/data/{subject}/ST000000/SE00001/MR* -s essai -f convertall.py -c dcm2niix -o output
INFO: Processing 0 dicoms
Traceback (most recent call last):
  File "/usr/local/bin/heudiconv", line 902, in <module>
    main()
  File "/usr/local/bin/heudiconv", line 898, in main
    min_meta=args.minmeta)
  File "/usr/local/bin/heudiconv", line 735, in convert_dicoms
    dcmfilter=getattr(mod, 'filter_dicom', None))
  File "/usr/local/bin/heudiconv", line 312, in process_dicoms
    lgr.info("Generated sequence info with %d entries", len(info))
UnboundLocalError: local variable 'info' referenced before assignment
![screenshot 2](https://user-images.githubusercontent.com/2786897/28170445-bac2f8d0-67e5-11e7-8e9f-0b3f74b29d02.png)

**Comment by satra** [comment]
@meribach - i think this has to do with volume mapping. i don't have a windows machine to test, but you should be mounting the outside folder into the container and then using the mount point inside the container to point to the dicoms. the `C:/Users/admin/data` is not going to be available inside the container. here are some details: https://rominirani.com/docker-on-windows-mounting-host-directories-d96f3f056a2c

the following command should work:
```
docker run --rm -it -v C:/Users/admin/data:/data nipy/heudiconv -d /data/{subject}/ST000000/SE00001/MR* -s essai -f convertall.py -c dcm2niix -o /data/output
```

note the changes to `-v`, `-d`, and `-o`

**Comment by meribach** [comment]
Dear Satra,
thanks a lot, you were right, i did not understand this mounting thing. Now I gave access to docker to that directory. It seems though that I am still doing Something wrong as now it creates the corresponding output/{subject}/info directory, but no files Inside, except another version of convertall.py. Maybe you have also an idea about what it could be. Let me know if I should open a new issue with this topic.
C:\Users\admin>docker run --rm -it -v C:/Users/admin/data:/data nipy/heudiconv -d /data/{subject}/ST000000/SE000000/* -s essai -f convertall.py -c dcm2niix -o /data/output
INFO: Processing 187 dicoms
Traceback (most recent call last):
  File "/usr/local/bin/heudiconv", line 902, in <module>
    main()
  File "/usr/local/bin/heudiconv", line 898, in main
    min_meta=args.minmeta)
  File "/usr/local/bin/heudiconv", line 735, in convert_dicoms
    dcmfilter=getattr(mod, 'filter_dicom', None))
  File "/usr/local/bin/heudiconv", line 312, in process_dicoms
    lgr.info("Generated sequence info with %d entries", len(info))
UnboundLocalError: local variable 'info' referenced before assignment

![screenshot 4](https://user-images.githubusercontent.com/2786897/28172804-f176ebbe-67ec-11e7-9183-2434d2a262de.png)

**Comment by satra** [comment]
try this, the convertall.py is in a strange location inside the container. 

```
docker run --rm -it -v C:/Users/admin/data:/data nipy/heudiconv -d /data/{subject}/ST000000/SE000000/* -s essai -f /tmp/convertall.py -c dcm2niix -o /data/output
```

if you want to use your own heuristic, you could do something like this:

```
docker run --rm -it -v C:/Users/admin/data:/data nipy/heudiconv -v C:/path/to/myheuristic.py:/heuristic.py -d /data/{subject}/ST000000/SE000000/* -s essai -f /heuristic.py -c dcm2niix -o /data/output
```

**Comment by andypotatohy** [comment]
Is this problem solved? I have the same issue, I'm running heudiconv without docker, but also get this error: UnboundLocalError: local variable 'info' referenced before assignment

Here is how I ran it:
heudiconv -d 'dicom/114356/D2005_11_17/MR/S0001_Localizer_9.683/*' -s test -o nifti/ -f ~/Downloads/heudiconv-master/heuristics/convertall.py -c none

**Comment by mgxd** [comment]
hi @andypotatohy - do you see the log `INFO: Processing 0 dicoms` in your output? if so, your dicoms are not being found. could you ensure the path specified with the -d flag exists (it may be as easy as making it an absolute path)

**Comment by andypotatohy** [comment]
Hi @mgxd , thanks for your reply. I did see the log INFO: Processing 27 dicoms in the output. The program did find the dicoms. So I was wondering it's a more general Python problem that I don't know how to fix (I'm pretty new to Python).

**Comment by mgxd** [comment]
@andypotatohy interesting - would it be possible for you to share those 27 dicoms? I've tried with some localizers I have but haven't been able to reproduce

**Comment by andypotatohy** [comment]
@mgxd Sorry I cannot share the dicoms. They are clinical data with patient info. The problem does not only happen to the localizers but to all the dicoms I have. So I was wondering if it's a potential bug in the program. Thanks!

**Comment by andypotatohy** [comment]
Oh btw, the data I have are breast MRI scans. I don't know if Heudiconv was designed only for converting human head MRIs. If yes, then maybe that's the reason it didn't work.

**Comment by neurolabusc** [comment]
I suggest you download MRIcroGL and use the import menu to convert your Dicom images to nifti. If this works, the issue is heudiconv, if it fails the issue is with dcm2niix and you can post the error messages on the dcm2niix github page

**Comment by satra** [comment]
@neurolabusc - dcm2niix doesn't get called when this flag is set `-c none`. so this is definitely a heudiconv issue. 

@mgxd - can you please track down under what conditions that line is called with the info variable undefined.
