### ISSUE TITLE
assert HEUDICONV_VERSION_JSON_KEY not in json_ AssertionError. XA30 subjects failing conversion.

### ISSUE THREAD

**Issue by Noah-Baden** [nipy/heudiconv#687]
### Summary

- [heuristic](https://github.com/nipy/heudiconv/files/11824803/heuristics.txt)

### Platform details:

Choose one:
- [O ] Local environment

OS : Ubuntu 18.04.6 LTS
Python version: 3.9.16
- [ ] Container

- Heudiconv version:

Heudiconv version .13.1

I've been trying to convert subjects using a Siemens fmri scanner with XA30 software. Something is going wrong when the jsons are being created, but I have not been able to figure out what. 

Here is the last part of the output I am getting.

`Traceback (most recent call last):
  File "/home/usr/badenn/.local/bin/heudiconv", line 8, in <module>
    sys.exit(main())
  File "/home/usr/badenn/.local/lib/python3.9/site-packages/heudiconv/cli/run.py", line 30, in main
    workflow(**kwargs)
  File "/home/usr/badenn/.local/lib/python3.9/site-packages/heudiconv/main.py", line 463, in workflow
    prep_conversion(
  File "/home/usr/badenn/.local/lib/python3.9/site-packages/heudiconv/convert.py", line 255, in prep_conversion
    convert(
  File "/home/usr/badenn/.local/lib/python3.9/site-packages/heudiconv/convert.py", line 635, in convert
    tuneup_bids_json_files(bids_outfiles)
  File "/home/usr/badenn/.local/lib/python3.9/site-packages/heudiconv/bids.py", line 334, in tuneup_bids_json_files
    assert HEUDICONV_VERSION_JSON_KEY not in json_
AssertionError `

Any help that can be given would be greatly appreciated.

**Comment by yarikoptic** [comment]
Do you remember by any chance the exact command line for the heudiconv invocation you have used? e.g. have you used `--overwrite` may be?  may be you have a log output handy somehow?

**Comment by Noah-Baden** [comment]
`heudiconv --files /path/to/dicoms -c dcm2niix -o /path/to/output -b notop -s 20071 -ss 53043 -f /path/to/heuristic/heuristics.py --overwrite`
[Here's the full output.](https://github.com/nipy/heudiconv/files/11872327/heuristic_error.txt) I have been using `--overwrite`

**Comment by yarikoptic** [comment]
great, so it is the `--overwrite` I suspected... I think that `assert` assumption was just wrong for such a case and we could just remove it... but need a quality minute for that or someone could submit a PR checking on that etc

**Comment by Noah-Baden** [comment]
Okay, I tried it without the `--overwrite`, but it still didn't work. It changed to a different error
[Heuristic_error_without_overwrite.txt](https://github.com/nipy/heudiconv/files/11875031/Heuristic_error_without_overwrite.txt) is the new output.

**Comment by yarikoptic** [comment]
well -- that one rightfully says correct thing:

```
❯ tail -n1 /tmp/Heuristic_error_without_overwrite.txt
RuntimeError: was asked to move /net/10.20.145.45/DOSENBACH03/GMT3/Noah/ASD_ADHD/sub-20071/ses-53043/func/sub-20071_ses-53043_task-rest_run-01_part-mag_bold_heudiconv547_e1a.nii.gz but destination already exists: /net/10.20.145.45/DOSENBACH03/GMT3/Noah/ASD_ADHD/sub-20071/ses-53043/func/sub-20071_ses-53043_task-rest_run-01_echo-1_part-mag_bold.nii.gz
```

are you trying to reconvert an existing subject/session or this is "from scratch" (whenever there is no `./sub-20071/ses-53043`)  for that subject session and somehow heuristic or heudiconv creates two conflicting destinations?

**Comment by yarikoptic** [comment]
if you have stored output from logging while running heudiconv -- does it mention that sub-20071_ses-53043_task-rest_run-01_echo-1_part-mag_bold.nii.gz twice?  What is your auto.edit.txt for this series? (didn't analyze heuristic thoroughly).  I wonder what to places decide that there is multiple identically named files.  may be your heuristic also manages to bring multiple sequences under the same name `sub-20071_ses-53043_task-rest_run-01_bold.nii.gz`?
