### ISSUE TITLE
NameError: global name 'URIRef' is not defined (nipype related)

### ISSUE THREAD

**Issue by chrisfilo** [nipy/heudiconv#7]
orange:heudiconv filo$ bin/heudiconv -d /Volumes/Samsung_T1/AA_dicoms/%s_*/*/*.dcm -s S4379IUI -f heuristics/convertall.py -o /tmp -c dcm2nii
	Converting /tmp/S4379IUI/run001
	/tmp/S4379IUI
	nii.gz
	dcm2nii
	150929-17:02:37,968 workflow INFO:
		 Executing node convert in dir: /var/folders/rw/dpbdbfb12p91tqb08078kww40000gn/T/heudiconvtmp7pAXZG/convert
	150929-17:02:37,989 workflow INFO:
		 Running: dcm2nii -a y -c y -b config.ini -v y -d y -e y -g y -i n -n y -o /private/var/folders/rw/dpbdbfb12p91tqb08078kww40000gn/T/heudiconvtmp7pAXZG/convert -p y -x n -f n /private/var/folders/rw/dpbdbfb12p91tqb08078kww40000gn/T/heudiconvtmp7pAXZG/convert/S4379IUI_1_1_00001_00001_124025357500_124030855000_4081835128.dcm
	Traceback (most recent call last):
	  File "bin/heudiconv", line 495, in <module>
	    anon_outdir=args.conv_outputdir)
	  File "bin/heudiconv", line 435, in convert_dicoms
	    mod, 'custom_callable', None))
	  File "bin/heudiconv", line 299, in convert
	    res = convertnode.run()
	  File "/Users/filo/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1428, in run
	    self._run_interface()
	  File "/Users/filo/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1538, in _run_interface
	    self._result = self._run_command(execute)
	  File "/Users/filo/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1664, in _run_command
	    result = self._interface.run()
	  File "/Users/filo/anaconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1082, in run
	    prov_record = write_provenance(results)
	  File "/Users/filo/anaconda/lib/python2.7/site-packages/nipype/utils/provenance.py", line 235, in write_provenance
	    ps.add_results(results)
	  File "/Users/filo/anaconda/lib/python2.7/site-packages/nipype/utils/provenance.py", line 288, in add_results
	    a0_attrs)
	  File "/Users/filo/anaconda/lib/python2.7/site-packages/nipype/external/provcopy.py", line 1846, in activity
	    return self.add_element(PROV_REC_ACTIVITY, identifier, {PROV_ATTR_STARTTIME: _ensure_datetime(startTime), PROV_ATTR_ENDTIME: _ensure_datetime(endTime)}, other_attributes)
	  File "/Users/filo/anaconda/lib/python2.7/site-packages/nipype/external/provcopy.py", line 1840, in add_element
	    return self.add_record(record_type, identifier, attributes, other_attributes)
	  File "/Users/filo/anaconda/lib/python2.7/site-packages/nipype/external/provcopy.py", line 1802, in add_record
	    new_record = PROV_REC_CLS[record_type](self, self.valid_identifier(identifier), attributes, other_attributes, asserted)
	  File "/Users/filo/anaconda/lib/python2.7/site-packages/nipype/external/provcopy.py", line 480, in __init__
	    self.add_attributes(attributes, other_attributes)
	  File "/Users/filo/anaconda/lib/python2.7/site-packages/nipype/external/provcopy.py", line 896, in add_attributes
	    ProvElement.add_attributes(self, attributes, extra_attributes)
	  File "/Users/filo/anaconda/lib/python2.7/site-packages/nipype/external/provcopy.py", line 576, in add_attributes
	    self.add_extra_attributes(extra_attributes)
	  File "/Users/filo/anaconda/lib/python2.7/site-packages/nipype/external/provcopy.py", line 567, in add_extra_attributes
	    attr_set = self.parse_extra_attributes(extra_attributes)
	  File "/Users/filo/anaconda/lib/python2.7/site-packages/nipype/external/provcopy.py", line 559, in parse_extra_attributes
	    for attribute, value in extra_attributes)
	  File "/Users/filo/anaconda/lib/python2.7/site-packages/nipype/external/provcopy.py", line 559, in <genexpr>
	    for attribute, value in extra_attributes)
	  File "/Users/filo/anaconda/lib/python2.7/site-packages/nipype/external/provcopy.py", line 537, in _auto_literal_conversion
	    if isinstance(literal, URIRef):
	NameError: global name 'URIRef' is not defined

**Comment by satra** [comment]
dependence on prov

**Comment by satra** [comment]
this should be addressed in issue #6

**Comment by hanke** [comment]
Agree. Quick fix is to install rdflib.

**Comment by hanke** [comment]
I am taking off the "bug" label.

**Comment by satra** [comment]
this is no longer an issue i believe.
