### ISSUE TITLE
Singularity/Dockerfile - Numpy / Nibabel conflict (v1.2.0 / v1.3.0)

### ISSUE THREAD

**Issue by SRSteinkamp** [nipy/heudiconv#794]
### Summary

I am getting the following error trying to run heudiconv with singularity: 

```python
Traceback (most recent call last):
  File "/opt/miniconda-py39_4.12.0/bin/heudiconv", line 5, in <module>
    from heudiconv.cli.run import main
  File "/src/heudiconv/heudiconv/cli/run.py", line 11, in <module>
    from ..main import workflow
  File "/src/heudiconv/heudiconv/main.py", line 11, in <module>
    from .bids import populate_bids_templates, populate_intended_for, tuneup_bids_json_files
  File "/src/heudiconv/heudiconv/bids.py", line 23, in <module>
    from . import __version__, dicoms
  File "/src/heudiconv/heudiconv/dicoms.py", line 47, in <module>
    import nibabel.nicom.dicomwrappers as dw
  File "/home/simons/.local/lib/python3.9/site-packages/nibabel/__init__.py", line 41, in <module>
    from . import analyze as ana
  File "/home/simons/.local/lib/python3.9/site-packages/nibabel/analyze.py", line 88, in <module>
    from .arrayproxy import ArrayProxy
  File "/home/simons/.local/lib/python3.9/site-packages/nibabel/arrayproxy.py", line 39, in <module>
    from .volumeutils import apply_read_scaling, array_from_file
  File "/home/simons/.local/lib/python3.9/site-packages/nibabel/volumeutils.py", line 23, in <module>
    from .casting import OK_FLOATS, shared_range
  File "/home/simons/.local/lib/python3.9/site-packages/nibabel/casting.py", line 723, in <module>
    OK_FLOATS = ok_floats()
  File "/home/simons/.local/lib/python3.9/site-packages/nibabel/casting.py", line 717, in ok_floats
    floats = np.sctypes['float'][:]
  File "/opt/miniconda-py39_4.12.0/lib/python3.9/site-packages/numpy/__init__.py", line 397, in __getattr__
    raise AttributeError(
AttributeError: `np.sctypes` was removed in the NumPy 2.0 release. Access dtypes explicitly instead.
```

It seems to me, that there is some conflict in the installation regarding nibabel and numpy installations. Heudiconv 1.16.0 seems to work, whereas 1.2.0 and 1.3.0 throw errors.

### Platform details:

Choose one:
- [ ] Local environment

- [x] Container

The following containers seem to be affected 1.3.0 and 1.2.0, there appears to be no error using 1.1.6.

- Heudiconv version:

The following containers seem to be affected 1.3.0 and 1.2.0, there appears to be no error using 1.1.6.

**Comment by yarikoptic** [comment]
```
  File "/src/heudiconv/heudiconv/dicoms.py", line 47, in <module>
    import nibabel.nicom.dicomwrappers as dw
  File "/home/simons/.local/lib/python3.9/site-packages/nibabel/__init__.py", line 41, in <module>
```

that is why I advise everyone to not install python libraries user wide.  At some point I even made `~/.local/lib/` owned by root and without write permission to avoid doing that by mistake.

So here singularity "by default" (?) bound mounted your `$HOME` and thus your local environment started to interact / being used inside the container environment. bad.  So try running with `--contain` or alike to not leak your outside (besides few specific paths) inside the container.  And/or `rm -rf ~/.local/lib/python*` to stay sane and healthy

**Comment by SRSteinkamp** [comment]
Great, thank you and sorry for the inconvenience. Good to know — no idea how I managed to install outside my conda environments - now I know what else to look for when stuff goes awry :) .
