### ISSUE TITLE
repeated "Missing required base classification time" error

### ISSUE THREAD

**Issue by andrew-yian-sun** [nipy/heudiconv#797]
### Summary

We're trying to convert a dataset which has a mix of modalities (T1, bold, dwi). Throughout the conversion process, we repeatedly get the following error: 
```
Traceback:
	Traceback (most recent call last):
	  File "/opt/miniconda-py39_4.12.0/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 397, in run
	    runtime = self._run_interface(runtime)
	  File "/opt/miniconda-py39_4.12.0/lib/python3.9/site-packages/nipype/interfaces/utility/wrappers.py", line 142, in _run_interface
	    out = function_handle(**args)
	  File "<string>", line 35, in embed_dicom_and_nifti_metadata
	  File "/opt/miniconda-py39_4.12.0/lib/python3.9/site-packages/dcmstack/dcmstack.py", line 1163, in parse_and_stack
	    results[key] = stack_group(group, warn_on_except, **stack_args)
	  File "/opt/miniconda-py39_4.12.0/lib/python3.9/site-packages/dcmstack/dcmstack.py", line 1117, in stack_group
	    result.add_dcm(dcm, meta)
	  File "/opt/miniconda-py39_4.12.0/lib/python3.9/site-packages/dcmstack/dcmstack.py", line 551, in add_dcm
	    nii_wrp = NiftiWrapper.from_dicom_wrapper(dw, meta)
	  File "/opt/miniconda-py39_4.12.0/lib/python3.9/site-packages/dcmstack/dcmmeta.py", line 1561, in from_dicom_wrapper
	    result = klass(nii_img, make_empty=True)
	  File "/opt/miniconda-py39_4.12.0/lib/python3.9/site-packages/dcmstack/dcmmeta.py", line 1280, in __init__
	    self.meta_ext.check_valid()
	  File "/opt/miniconda-py39_4.12.0/lib/python3.9/site-packages/dcmstack/dcmmeta.py", line 306, in check_valid
	    raise InvalidExtensionError('Missing required base '
	dcmstack.dcmmeta.InvalidExtensionError: The extension is not valid: Missing required base classification time
```
But heudiconv seems to keep going for a while, at least up until the end of one of the fMRI runs (not sure why it stops here). 

Here's the full output from the terminal:
[heudiconv_BAM118_conversion_log.txt](https://github.com/user-attachments/files/17548124/heudiconv_BAM118_conversion_log.txt)

### Platform details:

Choose one:
- [ ] Local environment

- [x] Container (Docker)

- Heudiconv version: 1.3.0

**Comment by yarikoptic** [comment]
if you do not care about extra metadata to be added beyond what `dcm2niix` already adds to the sidecar .json files -- use `--minmeta` option and this error should be gone.

I do not think it is anything we could address at heudiconv level, so I will just close, but feel free to channel it to dcmstack issues -- but ideally with details and/or samples on those dicoms
